<?php header('Content-Type: text/xml');?>
<?php echo '<?xml version="1.0" encoding="UTF-8"?>';?>
<kml xmlns="http://www.opengis.net/kml/2.2"
 xmlns:gx="http://www.google.com/kml/ext/2.2"> 
<Document>
<name><?php echo str_replace(' ','',$this->constituency) . '.kml';?></name>
<NetworkLink>
    <name>A KML file for all finds from the parliamentary constituency of <?php echo $this->constituency; ?></name>
    <Link>
      <href><?php echo $this->CurUrl();?></href>
    </Link>
  </NetworkLink>
<Style id="pushpin">
    <IconStyle id="mystyle">
      <Icon>
        <href>http://maps.google.com/mapfiles/kml/pushpin/ylw-pushpin.png</href>
        <scale>1.0</scale>
      </Icon>
    </IconStyle>
  </Style>
<?php echo $this->partialLoop('partials/xml/objectskml.phtml',$this->finds);?>
</Document>
</kml>