<?php 	$this->headTitle('My social web profiles');?>
<h2>My social profiles</h2>
<p>These social web service profiles will appear in my FOAF profile that this site generates. You can reuse this rdf profile for any other site that you wish to use.</p>

<p><a href="<?php echo $this->url(array('module' => 'users', 'controller' => 'social', 'action' => 'add'),'default',true);?>" title="Add a social web service">Add a new social web service.</a></p>
<?php if($this->services):?>
<table class="stripeMe" summary="My social web presence">
<caption>Social web presences</caption>
<thead>
<tr>
<th>Service</th>
<th>Service url</th>
<th>Account name</th>
<th>Actions</th>
</thead>
<tbody>
<?php echo $this->partialLoop('partials/contacts/social.phtml',$this->services);?>
</tbody>
</table>
<?php else:?>
<p>You haven't added a social web service to your profile!</p>
<?php endif;?>