<tr class="valid-<?php echo $this->valid;?>">
<td><?php echo $this->category;?></td>
<td><?php echo $this->timeagoinwords($this->created);?></td>
<td><?php echo $this->namethem($this->fullname);?></td>
<td><?php echo $this->timeagoinwords($this->updated);?></td>
<td><?php echo $this->namethem($this->fn);?></td>
<td><?php echo $this->validity($this->valid);?></td>
<td><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'numismatics','action' => 'editcategory','id' => $this->id),null,true);?>" title="Edit this category">Edit</a>
<?php $string = ' | <a href="'.$this->url(array('module' => 'admin','controller' => 'numismatics', 'action'=>'deletecategory','id' => $this->id),null,true).'" title="Delete this category">Delete</a>';
echo $this->allowedtest($string);?>
</td>
</tr>