<tr class="valid-<?php echo $this->publishState;?>">
<td><?php echo $this->title;?></td>
<td><?php echo $this->sectiontitle($this->section);?></td>
<td><?php echo $this->namethem($this->fullname);?></td>
<td><?php echo $this->timeagoinwords($this->created);?></td>
<td><?php echo $this->namethem($this->fn);?></td>
<td><?php echo $this->timeagoinwords($this->updated);?></td>
<td><?php echo $this->publish($this->publishState);?></td>
<td><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'help','action'=> 'edit','id' => $this->id),null,true);?>" title="Edit <?php echo $this->title;?>">Edit</a> <?php $string = ' | <a href="'.$this->url(array('module' => 'admin','controller' => 'help', 'action'=>'delete','id' => $this->id),null,true).'" title="Delete '. $this->title.'">Delete</a>';
echo $this->allowedtest($string);?>
</td>
</tr>