<tr class="valid-<?php echo $this->valid;?>">
<td><?php echo $this->escape($this->term);?></td>
<td><?php echo $this->timeagoinwords($this->created);?></td>
<td><?php echo $this->namethem($this->fullname);?></td>
<td><?php echo $this->timeagoinwords($this->updated);?></td>
<td><?php echo $this->namethem($this->fn);?></td>
<td><?php echo $this->validity($this->valid);?></td>
<td><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'terminology','action' => 'editculture','id' => $this->id),null,true);?>" title="Edit this ascribed cultural term">Edit</a> <?php  $string = ' | <a href="'.$this->url(array('module' => 'admin','controller' => 'terminology','action' => 'deleteculture','id' => $this->id),null,true).'" title="Delete ascribed culture">Delete</a>';
echo $this->allowedtest($string);?></td>
</tr>