<tr class="valid-<?php echo $this->valid;?>">
<td><?php echo $this->denomination;?></td>
<td><?php echo $this->timeagoinwords($this->created);?></td>
<td><?php echo $this->namethem($this->fullname);?></td>
<td><?php echo $this->timeagoinwords($this->updated);?></td>
<td><?php echo $this->namethem($this->fn);?></td>
<td><?php echo $this->validity($this->valid);?></td>
<td><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'numismatics','action' => 'editdenomination','id' => $this->id),null,true);?>" title="Edit this denomination">Edit</a> 
<?php 
$string = ' | <a href="'.$this->url(array('module' => 'admin','controller' => 'numismatics','action' => 'deletedenomination','id' => $this->id),null,true).'" title="Delete this denomination">Delete</a>';
echo $this->allowedtest($string);?></td>
</tr>