<tr class="valid-<?php echo $this->valid;?>">
<td><?php echo $this->escape($this->die_axis_name);?></td>
<td><?php echo $this->timeagoinwords($this->created);?></td>
<td><?php echo $this->namethem($this->fullname);?></td>
<td><?php echo $this->timeagoinwords($this->updated);?></td>
<td><?php echo $this->namethem($this->fn);?></td>
<td><?php echo $this->validity($this->valid);?>
<td><a href="<?php echo $this->url(array('module'=>'admin','controller' => 'numismatics','action'=>'editdieaxis', 'id'=>$this->id),null,true);?>" title="Edit this die axis term">Edit</a>
<?php $string = ' | <a href="'.$this->url(array('module'=>'admin','controller' => 'numismatics','action'=>'deletedieaxis', 'id'=>$this->id),null,true).'" title="Delete this die axis">Delete</a>';
echo $this->allowedtest($string);
?>
</td>
</tr>
