<tr class="valid-<?php echo $this->valid;?>">
<td><?php echo $this->escape($this->method);?></td>
<td><?php echo $this->timeagoinwords($this->created);?></td>
<td><?php echo $this->namethem($this->fullname);?></td>
<td><?php echo $this->timeagoinwords($this->updated);?></td>
<td><?php echo $this->namethem($this->fn);?></td>
<td><a href="<?php echo $this->url(array('module'=>'admin','controller' => 'terminology','action'=>'editmethod', 'id'=>$this->id),null,true);?>" title="Edit this term">Edit</a>
<?php
$string = '<a href="'.$this->url(array('module'=>'admin','controller' => 'terminology','action'=>'deletemethod', 'id'=>$this->id),null,true).'" title="Delete this term">Delete</a>';
echo $this->allowedtest($string);
?>
</tr>