<tr class="valid-<?php echo $this->valid;?>">
<td><?php echo $this->escape($this->dynasty);?></td>
<td><?php echo $this->adbc($this->escape($this->date_from));?></td>
<td><?php echo $this->adbc($this->escape($this->date_to));?></td>
<td><?php echo $this->timeagoinwords($this->created);?></td>
<td><?php echo $this->namethem($this->fullname);?></td>
<td><?php echo $this->timeagoinwords($this->updated);?></td>
<td><?php echo $this->namethem($this->fn);?></td>
<td><a href="<?php echo $this->url(array('module' => 'admin','controller'=>'numismatics','action'=>'editdynasty', 'id'=>$this->id),null,true);?>" title="Edit this term">Edit</a>
<?php
$string = '<a href="'.$this->url(array('module' => 'admin','controller'=>'numismatics','action'=>'deletedynasty', 'id'=>$this->id),null,true).'" title="Delete this term">Delete</a>';
echo $this->allowedtest($string);
?>
</tr>