<tr class="valid-<?php echo $this->valid;?>">
<td><?php echo $this->area. ' '.$this->region. ' ' .$this->tribe;?></td>
<td><?php echo $this->timeagoinwords($this->created);?></td>
<td><?php echo $this->namethem($this->fullname);?></td>
<td><?php echo $this->timeagoinwords($this->updated);?></td>
<td><?php echo $this->namethem($this->fn);?></td>
<td><?php echo $this->validity($this->valid);?></td>
<td><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'numismatics','action' => 'editregion','id' => $this->id),null,true);?>" title="Edit this <?php echo $this->region;?>">Edit</a> 
<?php
$string = ' | <a href="'.$this->url(array('module' => 'admin','controller' => 'numismatics','action' => 'deleteregion','id' => $this->id),null,true).'" title="Delete '.$this->region.'">Delete</a>';
echo $this->allowedtest($string);?>
</td>
</tr>