<tr class="valid-<?php echo $this->valid;?>">
<td><?php echo $this->term;?><br>
<strong><?php echo $this->oldID;?></strong></td>
<td><?php echo $this->timeagoinwords($this->created);?></td>
<td><?php echo $this->namethem($this->fullname);?></td>
<td><?php echo $this->timeagoinwords($this->updated);?></td>
<td><?php echo $this->namethem($this->fn);?></td>
<td><?php echo $this->validity($this->valid);?></td>
<td><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'terminology','action' => 'editlanduse','id' => $this->id),null,true);?>" title="Edit this landuse term">Edit</a> <?php $string = ' | <a href="'.$this->url(array('module' => 'admin','controller' => 'terminology','action' => 'deletelanduse','id' => $this->id),null,true).'" title="Delete this landuse term">Delete</a>';
echo $this->allowedtest($string);?></td>
</tr>