<tr id="comment-<?php echo $this->comment_ID;?>" class="status-<?php echo $this->comment_approved;?>">
<td class="author column-author" >
<?php $gravatar = new Gravatar($this->comment_author_email);
$gravatar->size = 30;
$gravatar->rating = "G";
echo $gravatar;
?>

<strong><?php echo $this->comment_author;?></strong><br/>
<?php if(isset($this->comment_author_url)) :?><a href="<?php echo $this->comment_author_url;?>" title="<?php echo $this->comment_author_url;?>"><?php echo $this->comment_author_url;?></a><br/><?php endif;?>
<a href="mailto:<?php echo $this->comment_author_email;?>"><?php echo $this->comment_author_email;?></a><br/>
<?php echo $this->user_ip;?></td>
<td class="comment column-comment"><div id="submitted-on">Submitted:<br />
<?php echo $this->comment_date ;?></div><?php echo 
$this->ellipsisstring(strip_tags($this->comment_content),200);?></td>
<td><?php if($this->replied == 1) { echo 'Replied '.$this->timeagoinwords($this->updated);} else { echo 'Reply needed';}?></td>
<td><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'messages',
'action' => 'reply','id' => $this->id),'default',true);?>" title="Reply to this message">Reply</a>
</td>
</tr>