<?php 
$ctrllr = $this->rulerperiod($this->t).'coins';
?>
<tr class="valid-<?php echo $this->valid;?>">
<td><?php echo $this->escape($this->mint_name).'<br> ' .$this->escape($this->t);?></td>
<td><?php echo $this->timeagoinwords($this->created);?></td>
<td><?php echo $this->namethem($this->fullname);?></td>
<td><?php echo $this->timeagoinwords($this->updated);?></td>
<td><?php echo $this->namethem($this->fn);?></td>
<td><?php echo $this->validity($this->valid);?>
<td><a href="<?php echo $this->url(array('module' => 'admin','controller'=>'numismatics','action'=>'editmint', 'id'=>$this->id),null,true);?>">Edit</a>
<?php $string = ' | <a href="'.$this->url(array('module' => 'admin','controller'=>'numismatics','action'=>'deletemint', 'id'=>$this->id),null,true).'" title="Delete this mint">Delete</a>';
echo $this->allowedtest($string);
?>
</td>
</tr>
