<tr>
<td><?php echo $this->ellipsisstring($this->quote,60);?></td>
<td><?php echo ucfirst($this->type);?></td>
<td><?php echo $this->niceshortdate($this->expire);?></td>
<td><?php echo $this->timeagoinwords($this->created);?></td>
<td><?php echo $this->namethem($this->fullname);?></td>
<td><?php echo $this->timeagoinwords($this->updated);?></td>
<td><?php echo $this->namethem($this->fn);?></td>
<td><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'quotes','action' => 'edit','id' => $this->id),null,true);?>" title="Edit this quote">Edit</a> 
<?php $string = ' | <a href="'.$this->url(array('module' => 'admin', 'controller' => 'quotes','action'=>'delete','id' => $this->id),null,true).'" title="Delete this quote">Delete</a>';
echo $this->allowedtest($string);?>

</td>
</tr>