<tr>
<td><?php echo $this->period_name. ' ' .$this->description;?></td>
<td><?php echo $this->timeagoinwords($this->created);?></td>
<td><?php echo $this->namethem($this->fullname);?></td>
<td><?php echo $this->timeagoinwords($this->updated);?></td>
<td><?php echo $this->namethem($this->fn);?></td>
<td><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'numismatics','action' => 'editreeceperiod','id' => $this->id),null,true);?>" title="Edit emperor biographical details">Edit</a> <?php $string = ' | <a href="'.$this->url(array('module' => 'admin','controller' => 'numismatics','action' => 'deletereeceperiod','id' => $this->id),null,true).'" title="Delete emperor biographical details">Delete</a>'; 
echo $this->allowedtest($string);?></td>
</tr>