<tr class="valid-<?php echo $this->valid;?>">
<td><a href="<?php echo $this->url(array('module' =>'admin','controller' => 'contacts','action' => 'role','id' => $this->id),null,true);?>" title="View all members assigned to <?php echo $this->role;?>"><?php echo $this->role;?></a></td>
<td><?php echo $this->timeagoinwords($this->created);?></td>
<td><?php echo $this->namethem($this->fullname);?></td>
<td><?php echo $this->timeagoinwords($this->updated);?></td>
<td><?php echo $this->namethem($this->fn);?></td>
<td><?php echo $this->validity($this->valid);?>
<td><a href="<?php echo $this->url(array('module' => 'admin','controller'=>'contacts','action'=>'editrole', 'id'=> $this->id),null,true);?>" title="Edit role">Edit</a>
<?php $string = ' | <a href="'.$this->url(array('module' => 'admin','controller'=>'contacts','action'=>'deleterole', 'id'=>$this->id),null,true).'" title="Delete this role">Delete</a>';
echo $this->allowedtest($string);
?>
</tr>