<tr>
<td><?php echo $this->type;?><br>Category: <em><?php echo $this->c;?></em></td>
<td><?php echo $this->timeagoinwords($this->escape($this->created));?></td>
<td><?php echo $this->namethem($this->fullname);?></td>
<td><?php echo $this->timeagoinwords($this->escape($this->updated));?></td>
<td><?php echo $this->namethem($this->fn);?>
</td>
<td><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'numismatics','action' => 'edittype','id' => $this->id),null,true);?>" title="Edit this category">Edit</a> 
<?php 
$string = ' | <a href="'.$this->url(array('module' => 'admin','controller' => 'numismatics','action' => 'deletetype','id' => $this->id),null,true).'"> Delete</a>';
$this->allowedTest($string);
?></td>
</tr>
