<?php echo $this->partial('partials/numismatics/typedetails.phtml', $this->types['0']);?>
<?php 
$this->jQuery()->addJavascriptFile($this->BaseUrl() . '/js/JQuery/jquery.lightbox.js',
$type='text/javascript'); 
?>
<?php $this->jQuery()->javascriptCaptureStart() ?>
jQuery(document).ready(function($) {
$('a[rel*=lightbox]').lightBox() 
});
<?php $this->jQuery()->javascriptCaptureEnd() ?>

<?php echo $this->latestRecords('type:' . $this->id);?>
