<?php echo $this->partial('partials/numismatics/typedetails.phtml', $this->types['0']);?>
<?php if($this->images):?>
<?php 
$this->jQuery()->addJavascriptFile($this->BaseUrl() . '/js/JQuery/jquery.lightbox.js',
$type='text/javascript'); 
?>
<?php $this->jQuery()->javascriptCaptureStart() ?>
jQuery(document).ready(function($) {
$('a[rel*=lightbox]').lightBox() 
});
<?php $this->jQuery()->javascriptCaptureEnd() ?>

<h3>Latest examples recorded</h3>
<div id="latest">
<?php echo $this->partialLoop('partials/database/imagesPaged.phtml',$this->images);?>
</div>
<?php endif;?>

