<h1>An error occurred</h1> 
<?php 
//Zend_debug::dump($this->params);
?>
<h2><?= $this->message ?></h2> 

<p><strong><?php echo $this->code;?></strong></p>

    <h3>Exception information:</h3> 
    <p> 
        <b>Message:</b> 
		<?= $this->exception->getMessage();
		$this->actionerrors()?> 
    </p> 

    <h3>Stack trace:</h3> 
    <p class="errors"><?= $this->exception->getTraceAsString() ?></p> 

    <h3>Request Parameters:</h3> 
    <p><? var_dump($this->request->getParams()) ?></p> 
