<?php $this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/confirm.js',$type = 'javascript');?>
<?php $this->jQuery()->javascriptCaptureStart();?>
$(document).ready(function(){
$('a.delete').click(function(e) {
		e.preventDefault();
		var parent =  $(this).parents("tr:first");
		$.ajax({
			type: 'get',
			url: '<?php echo $this->url(array('controller' => 'ajax','action' => 'deleteher'),null,true);?>',
			data: 'id=' + parent.attr('id').replace('signup-',''),
			beforeSend: function() {
				parent.animate({'backgroundColor':'#fb6c6c'},300);
			},
			success: function() {
				parent.slideUp(300,function() {
					parent.remove();
				});
			}
		});
	});
$('a.delete').confirm({
   dialogShow:'fadeIn',
    dialogSpeed:'slow',
    buttons: {
      wrapper:'<button></button>',
      separator:'  '
    }  
  });
 });


<?php 
	$this->headTitle('Authorities signed up for data transfer');
$this->jQuery()->javascriptCaptureEnd();?>

<h2>Historic Environment Records signup</h2>
<?php 
$string = '<p><a href="';
$string .= $this->url(array('module' => 'admin','controller' => 'her','action' => 'add'),null,true);
$string .= '" title="Add a new signatory">Add a signatory</a></p>';
echo $this->allowedtest($string);
?>
<?php if (count($this->hers)): ?>

<table class="stripeMe" summary="This table lists all the HERs that have signed up to our data transfer agreement">
<caption>Signed up HER offices</caption>
<thead>
<tr>
<th>Authority</th>
<th>Signatory</th>
<?php 
$string = '<th>Actions</th>';
echo $this->allowedtest($string);?>

</tr>
</thead>
<tbody>
<?php echo $this->partialLoop('partials/research/hers.phtml',$this->hers);?>
</tbody>
</table>
<?php else:?>
<p>No sign up data is available to you.</p>
<?php endif; ?>
<?= $this->paginationControl($this->hers, 'Sliding', 'structure/pagination.phtml'); ?>
