<?php 
/** View for displaying an individual category
*/
?>
<?php echo $this->partialLoop('partials/numismatics/category.phtml',$this->categories);?>

<p><?php echo $this->partialLoop('partials/count.phtml',$this->counts);?></p>

<h3>Associated rulers</h3>
<ul id="related">
<?php echo $this->partialLoop('partials/numismatics/rulers.phtml', $this->rulers) ?>
</ul>
<h3>Types of coin associated with this category</h3>
<ul id="related">
<?php echo $this->partialLoop('partials/numismatics/types.phtml', $this->types) ?>

</ul>
