<div style="width:650px;height:400px;overflow:auto;"?>
<h2>Audit changes made <?php echo $this->timeagoinwords($this->audit['0']['created']);?></h2>
<p>All changes made by <?php echo $this->audit['0']['fullname'];?></p>
<table class="stripeMe" summary="A list of changes" style="width:100%;">
<thead>
<tr>
<th>Field name</th>
<th>Before change</th>
<th>After change</th>
<tr>
</thead>
<?php foreach($this->audit as $a):?>
<tr>
<td><?php echo ucfirst($a['fieldName']);?></td>
<td><?php echo $a['beforeValue'];?></td>
<td><?php echo $a['afterValue'];?></td>
</tr>
<?php endforeach;?>
</table>
</div>