<div id="nearest">
<h2>Artefacts found by this finder</h2>
<div id="nested">
<?php if (count($this->finds) > 0) : ?>

<p>This finder has <?php echo $this->partialLoop('partials/quantity.phtml', $this->quants) ?> objects recorded within <?php echo count($this->finds);?> records.</p>

<ul id="related">
<?php echo $this->partialLoop('partials/database/otherfinds.phtml', $this->finds) ?>
</ul>
<?php else: ?>
<p class="error">No records found for this finder.</p>
<?php endif;?>
</div>
</div>