<?php 
$this->headTitle('People registered with the Scheme');
$this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/jquery.autocomplete.pack.js',$type='text/javascript');
$this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/autocompleteinitpeople1.js',$type='text/javascript'); 
$this->headLink()->appendStylesheet($this->baseUrl().'/css/autocomplete.css')
?>
<h2>People registered with the Scheme</h2>

<?php echo $this->peopletoolbox();?>
<div id="findsList">
<?php if (count($this->paginator)): ?>
<table class="stripeMe" summary="All people registered on our database">
<thead>
<tr>
<th>Name</th>
<th>County</th>
<th>Organisation</th>
<th>Primary activity</th>
<th>Actions</th>
</tr>
</thead>
<tr>
<?php echo $this->form;?>
</tr>
<tbody>
<?php echo $this->partialLoop('partials/database/peopleTableList.phtml',$this->paginator);?>
</tbody>
</table>
<?php else :?>
<p>There are no people registered or available to you.</p>
<?php endif; ?>
<?= $this->paginationControl($this->paginator, 'Sliding', 'structure/pagination.phtml'); ?>
</div>