<?php echo $this->partialLoop('partials/database/personDetails.phtml',$this->peoples);?>
<?php if(count($this->finds)) :?>
<h3>Finds recorded with the Scheme</h3>


<table summary="A list of all finds recorded by this finder" class="stripeMe">
<caption>A list of finds for this finder</caption>
<thead>
<tr>
<th>Image</th>
<th>Object type</th>
<th>Find number</th>
<th>Broadperiod</th>
<th>County</th>
<th>Actions</th>
</thead>
</tr>
<tbody>
<?php echo $this->partialLoop('partials/database/findsTable.phtml',$this->finds);?>
</tbody>
</table>
<?php $this->paginationControl($this->finds, 'Sliding', 'structure/pagination.phtml'); ?>

<?php else:?>
<p>This finder has not reported any objects yet.</p>
<?php endif;?>