<?php 
$this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/jquery.lightbox.js',$type='text/javascript'); 
$this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/jquery.autocomplete.pack.js',$type='text/javascript');
$this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/autocompleteinit.js',$type='text/javascript'); 
$this->headLink()->appendStylesheet($this->baseUrl().'/css/autocomplete.css');

?>
<?php $this->jQuery()->javascriptCaptureStart() ?>
jQuery(document).ready(function($) {
 $('a[rel*=lightbox]').lightBox() 
    })
<?php $this->jQuery()->javascriptCaptureEnd() ?>

<h2>All finds and coins recorded by <?php echo $this->fullname();?></h2>

<?php echo $this->loggedinlinks();?>

<?php if($this->params != NULL):?>
<?php echo $this->SearchParams($this->params);?>
<?php endif;?>

<div id="findsList">
<?php if (count($this->paginator)): ?>
<table class="stripeMe" summary="A complete list of finds and coins recorded">
<thead>
<tr> 
<th>Image</th>
<th>Object Type</th>
<th>Find number</th>
<th>Broadperiod</th>
<th>County</th>
<th>Actions</th>
</tr>
</thead>
<tr><td></td><?php echo $this->form;?></tr>  
<tbody>
<?php echo $this->partialLoop('partials/database/findsTable.phtml',$this->paginator);?>
</tbody>
</table>
<?php endif; ?>
</div>


<?= $this->paginationControl($this->paginator, 'Sliding', 'structure/pagination.phtml'); ?>