<?php 
$this->headTitle('Profile for Emperor:  '.$this->name);
$this->headMeta('Biographical and related data for '.$this->name,'DC.Description');
$this->headMeta('roman,numismatics,biography,emperor,'.$this->name.',portable antiquities','DC.Keywords');

$this->headLink()->appendAlternate($this->url(array('module' => 'database','controller' => 'search','action' => 'results','ruler' => $this->pasID,'format' => 'rss'),null,true), 'application/rss+xml', 'Latest finds for '. $this->name .'- RSS Feed'); ?>
<h2><?php echo $this->escape($this->name);?></h2>
<?php if(isset($this->p)):?>
<p>Reece Period attributed: <a href="<?php echo $this->url(array('module' => 'romancoins','controller' => 'reeceperiods','action' => 'period','id'=> $this->reeceID, 'name' => $this->urlslug($this->p)),'default',true);?>" title="View scope notes for <?php echo $this->p;?>"><?php echo $this->escape($this->p);?></a></p>
<?php endif;?>

<?php if ($this->filename != NULL) {
list($w, $h) = getimagesize('./images/rulers/resized/'.$this->escape($this->filename));
echo '<a href="'.$this->baseUrl().'/images/rulers/'.$this->escape($this->filename).'" "title="View high resolution image of '. $this->name.'" rel="lightbox"><img src="'.$this->baseUrl().'/images/rulers/resized/'.$this->escape($this->filename).'" class="portrait" alt="Obverse image of a coin of '. $this->name.'" width="'.$w.'" height="'.$h.'" /></a>';
}
?>
<p>Member of the <a href="<?php echo $this->url(array('module' => 'romancoins','controller' => 'dynasties','action' => 'dynasty', 'id' => $this->i),null,true);?>" title="View details for the <?php echo $this->dyn;?>"><?php echo $this->escape($this->dyn);?></a> dynasty.</p>
<p>Coins for this issuer were issued from <?php echo $this->escape($this->date_from);?> until <?php echo $this->escape($this->date_to);?>.</p>

<?php echo $this->biography;?>

<p>View <a href="<?php echo $this->url(array('module' => 'database','controller' => 'search','action' => 'results','ruler' => $this->pasID),null, true);?>" title="Search for all coins of <?php echo $this->name;?>">all coins recorded</a> by the scheme attributed to <?php echo $this->name;?>.</p>
<?php 
ini_set('display_errors', '0');     # don't show any errors...
error_reporting(E_ALL | E_STRICT);  # ...but do log them		
$config = array('remote_store_endpoint' => 'http://dbpedia.org/sparql');
$store = ARC2::getRemoteStore($config);
//build the SPARQL query
$q = '
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX : <http://dbpedia.org/resource/>
PREFIX dbpedia2: <http://dbpedia.org/property/>
PREFIX dbpedia: <http://dbpedia.org/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dbpedia-owl: <http://dbpedia.org/ontology/>

SELECT *

WHERE {
?king foaf:page <http://en.wikipedia.org/wiki/'.urlencode(str_replace(array(' (first reign)',' (second reign)',' '),array('','','_'),ucfirst($this->name))).'> .
OPTIONAL {?king dbpedia-owl:abstract ?abstract} .
OPTIONAL {?king foaf:depiction ?depiction}.
OPTIONAL {?king dbpedia-owl:thumbnail ?thumb} .
OPTIONAL {?king dbpedia2:imgw ?imgw} .


?king foaf:page ?page.
FILTER langMatches( lang(?abstract), "en") 

}
LIMIT 1
';
//process the results

//Zend_Debug::dump($q);
$results = array();
if ($rows = $store->query($q, 'rows')) {
foreach ($rows as $row) {
//Zend_Debug::dump($row);
$chunks = split('\. ',str_replace('c.','circa',$row['abstract']));
  foreach($chunks as $key=>$c){
    $chunks[$key] = ($key%3==0) ? ($c . '.</p><p>') : ($c.'. ');
  }
 $abs = '<p>'.join($chunks).'</p>';
echo '<h4>Wikipedia derived information</h4>';
if(isset($row['thumb'])) {
echo '<a href="'.$row['depiction'].'" rel="lightbox" title="' .str_replace('"','',$row['caption']) .'"><img src="'.$row['thumb'].'" class="flow" alt="' .str_replace('"','',$row['caption']) .'" width="'.$row['imgw'].'"/></a>';
}
echo '<p>'.$abs.'</p>';
echo '<p>';
if(isset($row['title'])) {
echo 'Title: '. $row['title'] . '<br />';
}
//echo 'Patronage: '.$row['patronage'].'<br />';
if(isset($row['reign'])) {
echo 'Exact reign: '.strip_tags(rawurldecode(str_replace(array('http://dbpedia.org/resource/','_'),array('',' '),$row['reign']))).'<br />';
}
if(isset($row['years'])){
echo 'Years ruled: '.rawurldecode($row['years']).'<br />';
}
if(isset($row['spouse'])){
echo 'Spouse: '.rawurldecode(str_replace(array('http://dbpedia.org/resource/','_'),array('',' '),strip_tags($row['spouse']))).'<br />';
}
if(isset($row['bp'])) {
echo 'Birth place: '.str_replace(array('http://dbpedia.org/resource/','_'),array('',' '),rawurldecode($row['bp'])).'<br />';
}
if(isset($row['mother'])){
echo 'Mother: '.str_replace(array('http://dbpedia.org/resource/','_'),array('',' '),rawurldecode($row['mother'])).'<br />';
}
if(isset($row['father'])){
echo 'Father: '.rawurldecode(str_replace(array('http://dbpedia.org/resource/','_'),array('',' '),$row['father'])).'<br />';
}
if(isset($row['successor'])) {
echo 'Succeeded by: ' .str_replace(array('http://dbpedia.org/resource/','_'),array('',' '),$row['successor']).'<br />';
}
if(isset($row['burial'])){
echo 'Burial place: '.rawurldecode(str_replace(array('http://dbpedia.org/resource/','_'),array('',' '),$row['burial'])).'<br />';
}
if(isset($row['dob'])) {
echo 'Date of birth: '.$row['dob'].'<br />';
}
if(isset($row['dod'])) {
echo 'Date of death: '.$row['dod'].'<br />';
}
if(isset($row['dp'])) {
echo 'Died at: '.rawurldecode(str_replace(array('http://dbpedia.org/resource/','_'),array('',' '),$row['dp'])).'<br />';
}

if(isset($row['alt'])) {
echo 'Alternative names: '.$row['alt'].'<br />';
}
echo 'Wikipedia page: <a href="'.$row['page'].'" title="Go to the Wikipedia entry for '.$row['name'].'">'.$row['page'].'</a><br />';

echo 'This data is sourced from dbpedia, and as such should be treated with caution';
echo '</p>';
}
}
?> 


