<?php $this->headTitle('Details for Roman mint at '.$this->name);
$this->headMeta('Full details for Roman mint at '.$this->name . ' describing location and recent examples. ','dc.description')
->headMeta('CC NC-SA-BY','dc.rights')
->headMeta('The Portable Antiquities Scheme','dc.publisher')
->headMeta('Daniel Pett','dc.creator');

?>

<h2>The <?php echo $this->escape($this->name);?> mint</h2>

<p>Mint: <?php echo $this->escape($this->name);?> <br>
Geo location: <?php echo $this->escape($this->latitude);?> <?php echo $this->escape($this->longitude);?><br>
Abbreviation: <?php echo $this->abbrev;?><br>
<?php echo $this->description;?></p>
<p>View <a href="<?php echo $this->url(array('module'=>'database','controller' => 'search','action'=>'results', 'mint'=>$this->pasID),null,true);?>" title="View all records">all coins recorded</a>, which are attributed to <?php echo $this->escape($this->name);?>.</p>
