<tr>
<td>
<a href="<?php echo $this->url(array('module' => 'romancoins','controller' => 'reeceperiods',
'action'=>'period', 'id'=>$this->id),null,true);?>" title="View details for <?php echo $this->escape($this->period_name); ?>" ><?php echo $this->escape($this->period_name); ?> [<?php echo $this->escape($this->description); ?>]</a>
</td>
<td>
<strong><?php echo $this->quantity; ?></strong>
</td>
</tr>
