<?php
$site = Zend_Registry::get('siteurl');
$module = Zend_Controller_Front::getInstance()->getRequest()->getModuleName();	
$controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();	
$action = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
$contextSwitch = Zend_Controller_Action_HelperBroker::getStaticHelper('ContextSwitch');	
$param = Zend_Controller_Front::getInstance()->getRequest()->getParam('id');
$contexts = $contextSwitch->getContexts();
$dom = new DomDocument("1.0", "UTF-8");
$mints  = $dom->createElement('response');
$meta = $dom->createElement('meta');
$mints->appendChild($meta);
$meta->appendChild( $dom->createElement('generated', date(DATE_W3C,time())));
$formats = $dom->createElement('formats');
$meta->appendChild($formats);	
foreach ($contexts as $k => $v){
$formats->appendChild( $dom->createElement($k, $site . $this->url(array('module' => $module,
'controller' => $controller,'action' => $action,'id' => $param,'format' => $k),NULL,true)  ));
}
$formats->appendChild( $dom->createElement('html', $site . $this->url(array('module' => $module,
'controller' => $controller,'action' => $action,'id' => $param),NULL,true)  ));
$mintsElem = $dom->createElement('mints');

foreach($this->mints as $m){
$m = (object)$m;
$mintElem = $dom->createElement('mint');
$mintElem->appendChild( $dom->createElement('id', $m->i));
$mintElem->appendChild( $dom->createElement('name', $m->name));
$mintElem->appendChild( $dom->createElement('created', $m->created));
$mintElem->appendChild( $dom->createElement('updated', $m->updated));
$mintElem->appendChild( $dom->createElement('period', $m->p));
$imageElem = $dom->createElement('recentRecords');	
$mintElem->appendChild($imageElem);

foreach($this->images as $i){
$i = (object)$i;
$recordElem = $dom->createElement('record');
$imageElem->appendChild( $recordElem);
$recordElem->appendChild( $dom->createElement('findID', $i->old_findID));
$recordElem->appendChild( $dom->createElement('objectType', $i->objecttype));
$recordElem->appendChild( $dom->createElement('broadPeriod', $i->broadperiod));
$recordElem->appendChild( $dom->createElement('url', $site . '/database/artefacts/record/id/' . $i->id));
$recordElem->appendChild( $dom->createElement('thumbnail', $site . ' /images/' . $i->id . '.jpg'));
}
$mints->appendChild( $mintElem );
}

$dom->appendChild( $mints );

$xmlData  = $dom->saveXML();
echo $xmlData;
