<?php 
$this->headTitle('An introduction to our photos');
$this->MetaBase('The Scheme curates a large number of images on it\'s flickr profile feed. 
They are all produced under a Creative Commons licence, feel free to use them - except for commercial use',
'Photos',
'flickr,photos,archaeology,numismatics,coins,museums');?>

<?php $this->jQuery()->javascriptCaptureStart() ?>
jQuery(document).ready(function($) {
$('a[rel*=lightbox]').lightBox() 
});
<?php $this->jQuery()->javascriptCaptureEnd() ?>

<?php 
$this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/jquery.lightbox.js',$type='text/javascript'); 
?>

<h2>The Scheme on Flickr</h2>
<?php 
$config = Zend_Registry::get('config')->webservice->flickr;
echo $this->flickrFront($config);
echo $this->flickrTags($config);
echo $this->flickrContactsList($config);
?>

