<?php
$this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/jQueryLinkedSelect.js',$type='text/javascript'); 
$this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/coinslinkedselect.js',$type='text/javascript'); 
$this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/linkedinit.js',$type='text/javascript');
$this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/iacoinslinkedinit.js',$type='text/javascript');
$this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/jquery.autocomplete.pack.js',$type='text/javascript');
$this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/autocompleteinit.js',$type='text/javascript');  
$this->headLink()->appendStylesheet($this->baseUrl().'/css/autocomplete.css')
	->appendStylesheet($this->baseUrl().'/css/ui.datepicker.css');
?>
<h2>Add a findspot</h2>
<p>You can copy your <a href="<?php echo $this->url(array('module' => 'database','controller' => 'findspots','action' => 'add','copy' => 'last'),null,false);?>" title="Autofill form fields from last record you created" id="populate" accesskey="c">last record</a></p>
<?php 
echo $this->form;
?>