<?php
$site = Zend_Registry::get('siteurl');
$module = Zend_Controller_Front::getInstance()->getRequest()->getModuleName();	
$controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();	
$action = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
$contextSwitch = Zend_Controller_Action_HelperBroker::getStaticHelper('ContextSwitch');	
$param = Zend_Controller_Front::getInstance()->getRequest()->getParam('id');
$contexts = $contextSwitch->getContexts();

$dom = new DomDocument("1.0", "UTF-8");
$moneyers  = $dom->createElement('response');

$meta = $dom->createElement('meta');
$moneyers->appendChild($meta);
$meta->appendChild( $dom->createElement('generated', date(DATE_W3C,time())));
$formats = $dom->createElement('formats');
$meta->appendChild($formats);	
foreach ($contexts as $k => $v){
$formats->appendChild( $dom->createElement($k, $site . $this->url(array('module' => $module,
'controller' => $controller,'action' => $action,'id' => $param,'format' => $k),NULL,true)  ));
}
$formats->appendChild( $dom->createElement('html', $site . $this->url(array('module' => $module,
'controller' => $controller,'action' => $action,'id' => $param),NULL,true)  ));

foreach($this->moneyer as $moneyer){
$moneyer = (array)$moneyer;
$moneyerElem = $dom->createElement('moneyer');
$moneyerElem->appendChild( $dom->createElement('id', $moneyer['id']));
$moneyerElem->appendChild( $dom->createElement('name', $moneyer['name']));
$moneyerElem->appendChild( $dom->createElement('mint', $moneyer['mint']));
$moneyerElem->appendChild( $dom->createElement('alternativeName', $moneyer['alt_name']));
$moneyerElem->appendChild( $dom->createElement('dateFrom', $moneyer['date_1']));
$moneyerElem->appendChild( $dom->createElement('dateTo', $moneyer['date_2']));
$moneyerElem->appendChild( $dom->createElement('biography', $moneyer['bio']));
$moneyerElem->appendChild( $dom->createElement('rrcReference', $moneyer['RRC']));
$moneyerElem->appendChild( $dom->createElement('appearance', $moneyer['appear']));
$moneyerElem->appendChild( $dom->createElement('updated', $moneyer['updated']));
$moneyerElem->appendChild( $dom->createElement('created', $moneyer['created']));

$imageElem = $dom->createElement('recentRecords');	
$moneyerElem->appendChild($imageElem);

foreach($this->images as $i){
$i = (object)$i;
$recordElem = $dom->createElement('record');
$imageElem->appendChild( $recordElem);
$recordElem->appendChild( $dom->createElement('findID', $i->old_findID));
$recordElem->appendChild( $dom->createElement('label', $i->label));
$recordElem->appendChild( $dom->createElement('objectType', $i->objecttype));
$recordElem->appendChild( $dom->createElement('broadPeriod', $i->broadperiod));
$recordElem->appendChild( $dom->createElement('url', $site . '/database/artefacts/record/id/' . $i->id));
$recordElem->appendChild( $dom->createElement('thumbnail', $site . ' /images/' . $i->id . '.jpg'));
}
$moneyers->appendChild( $moneyerElem );
}

$dom->appendChild( $moneyers  );

$xmlData  = $dom->saveXML();
echo $xmlData;
