<?php echo $this->partial('partials/numismatics/moneyer.phtml',$this->moneyer['0']);
echo $this->latestRecords('moneyer:' .  Zend_Controller_Front::getInstance()->getRequest()->getParam('by'));
$this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/jquery.lightbox.js',$type='text/javascript'); 
$this->jQuery()->javascriptCaptureStart(); 
?>
jQuery(document).ready(function($) {
$('a[rel*=lightbox]').lightBox() 
});
<?php $this->jQuery()->javascriptCaptureEnd(); ?>