<?php $this->jQuery()->javascriptCaptureStart() ?>
jQuery(document).ready(function($) {
$('a[rel*=lightbox]').lightBox() 
});
<?php 
$this->jQuery()->javascriptCaptureEnd();
$this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/jquery.lightbox.js',$type='text/javascript'); 
?>
<?php echo $this->partialLoop('partials/numismatics/romanDenom.phtml', $this->denoms) ;?>
<h3>Issued by</h3>
<ul id="related">
<?php echo $this->partialLoop('partials/numismatics/rulerDenom.phtml', $this->rulers);?>
</ul>
<?php echo $this->latestRecords('denomination:' .  Zend_Controller_Front::getInstance()->getRequest()->getParam('id'));?>