
<h2><?php echo $this->image->photo->title;?></h2>
<a href="<?php echo $this->sizes->size['5']->source;?>" rel="lightbox" title="View larger version"><img src="<?php echo $this->sizes->size['3']->source;?>" width="<?php echo $this->sizes->size['3']->width;?>" 
height="<?php echo $this->sizes->size['3']->height;?>" alt="<?php echo $this->image->photo->title;?>" /></a>

<p>View on flickr: <?php echo $this->FlickrVariantSizes($this->sizes->size );?></p>


<?php if(isset($this->geo->location)):?>
<p><?php echo $this->image->photo->description;?></p>
<h4>Geo location of the photo</h4>
<?php 
$parameters = array(
'size' => array( '300', '300'),
'zoom' => 12,
'maptype' => 'hybrid',
'markers' => array (array($this->geo->location->latitude ,$this->geo->location->longitude))
);
echo $this->GoogleStaticMap($parameters);?>
<?php endif;?>

<h3>Metadata</h3>
<ul>
<li>Views: <?php echo $this->image->photo->views;?></li>
<li>License: <?php echo $this->FlickrLicense((int)$this->image->photo->license);?></li>
<li>Taken by: <?php echo $this->image->photo->owner->realname;?></li>
<li>Uploaded: <?php echo $this->niceshortdate($this->image->photo->dateuploaded);?></li>
<li>Taken on: <?php echo $this->niceshortdate($this->image->photo->dates->taken);?></li>
<?php if(!is_null($this->image->photo->tags)):?>
<li>Tagged: <?php echo $this->flickrTagDetails($this->image->photo->tags->tag);?></li>
<?php endif;?>
<li>Image permissions: <?php echo $this->flickrPerms($this->image->photo->usage);?></li>
</ul>

<?php if($this->image->photo->comments):?>
<h3>Comments</h3>
<ul>
<?php echo $this->FlickrPhotoComments($this->comments);?>
</ul>
<?php endif;?>

<?php if($this->exif):?>
<h3>Exif details</h3>
<?php if($this->exif->camera):?>
<p>This image was taken with: <?php echo $this->exif->camera;?></p>
<?php endif;?>
<h4>Tags</h4>
<ul>
<?php echo $this->FlickrTagExif($this->exif->exif);?>
</ul>
<?php endif;?>