<?php $this->jQuery()->javascriptCaptureStart() ?>
jQuery(document).ready(function($) {

 $('a[rel*=lightbox]').lightBox() 
    })
<?php $this->jQuery()->javascriptCaptureEnd() ?>
<?php 
$this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/jquery.lightbox.js',$type='text/javascript'); 
?>

<?php $this->headTitle('Information on the group' . $this->name);
$this->MetaBase('A list of the first 100 photos retrieved from the flickr api via YQL for the group ' . $this->name,
'photos',
'photos,flickr,groups,api,yql,' . $this->name);?>
<h2>Details for the <?php echo $this->name;?> group</h2>
<img src="http://farm<?php echo $this->iconfarm;?>.static.flickr.com/<?php echo $this->iconserver;?>/buddyicons/<?php echo $this->id;?>.jpg" height="48" width="48" alt="<?php echo $this->name;?>'s buddy icon" style="float:left;padding:5px;"/><p><strong>This group is described as: </strong><?php echo $this->desc;?></p>
<p>Stats: This group has <?php echo $this->members;?> members.</p>
<h3>Group pool photos</h3>
<?php if(count($this->photos)):?>
<?php 
echo $this->partialLoop('partials/flickr/favourite.phtml',$this->photos);
?> 
<?php echo $this->paginationControl($this->photos, 'Sliding', 'structure/pagination.phtml'); ?>

<?php else:?>
<p>There are no photos available for that place.</p>
<?php endif;?>