<?php 
$this->jQuery()->javascriptCaptureStart();
?>
jQuery(document).ready(function($) {
$('a[rel*=lightbox]').lightBox() 
});
<?php $this->jQuery()->javascriptCaptureEnd() ?>
<?php 
$this->jQuery()->addJavascriptFile($this->baseUrl() . '/js/JQuery/jquery.lightbox.js',$type='text/javascript'); 
?>
<?php $this->FlickrSetInfo($this->pictures->photoset->id);?>
<?php if(count($this->pictures)):?>
<?php 
$photos = array();
foreach($this->pictures->photoset->photo as $photo){
	$photos[] = (array)$photo;
}
echo $this->partialLoop('partials/flickr/set.phtml',$photos);?>
<?php echo $this->paginationControl($this->paginator, 'Sliding', 'structure/pagination.phtml'); ?>

<?php else:?>
<p>There are no photos available with that tag.</p>
<?php endif;?>
