<?php 
$this->jQuery()->javascriptCaptureStart();
?>
jQuery(document).ready(function($) {
$('a[rel*=lightbox]').lightBox() 
});
<?php $this->jQuery()->javascriptCaptureEnd() ?>
<?php 
$this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/jquery.lightbox.js',$type='text/javascript'); 
?>
<?php 
$this->headTitle('The Scheme\'s favourite images');
$this->MetaBase('A list of our favourite archaeological images that we\'ve seen on flickr. This should only
show creative commons licenced images.',
'photos',
'photos,archaeology,favourites,portable antiquities,flickr');
?>

<h2>Archaeology images from around the world.</h2>
<div>
<?php
if($this->photos):
?>
<?php 
$photos = array();
foreach($this->photos->photo as $photo){
	$photos[] = (array)$photo;
}
echo $this->partialLoop('partials/flickr/favourite.phtml',$photos);
?> 
</div>
<?php echo $this->paginationControl($this->paginator, 'Sliding', 'structure/pagination.phtml'); ?>

<?php else:?>
<p>There are no favourites available at the moment</p>
<?php endif;?>