<?php $this->jQuery()->javascriptCaptureStart() ?>
jQuery(document).ready(function($) {

 $('a[rel*=lightbox]').lightBox() 
    })
<?php $this->jQuery()->javascriptCaptureEnd() ?>
<?php 
$this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/jquery.lightbox.js',$type='text/javascript'); 
$this->headTitle('Our sets of images as seen on Flickr');
$this->MetaBase('A collection of our sets of photos as shown on flickr and consumed within our site. It includes the mighty Staffordshire Hoard',
'photos',
'archaeology,museum,treasure,objects,staffordshire,hoard,frome')


?>
<h2>Scheme photo sets on flickr</h2>

<?php if($this->data):?>
<div >
<?php foreach($this->data as $d) :?>
<div class="set">
<h3><?php echo $d['title'];?></h3>
<p>
<a href="<?php echo $this->FlickrImage($d['farm'],$d['server'],$d['primary'],$d['secret'],'b');?>" title="View image in larger format" rel="lightbox"><img src="http://farm<?php echo $d['farm'];?>.static.flickr.com/<?php echo $d['server'];?>/<?php echo $d['primary'];?>_<?php echo $d['secret'];?>_m.jpg" alt="Primary image for this set" style="float:right;" class="tmb" /></a>
<?php echo $this->ellipsisstring($d['description'],500);?><br />
This set contains <?php echo $d['photos'];?> photographs<?php if($d['videos'] != 0) { echo ' and '.$d['videos'].' videos';} else { echo '.';}?> <br />  
<a href="<?php echo $this->FlickrSetUrl($d['id']);?>" title="View this set in context">View this set on flickr.</a> | <a href="<?php echo $this->url(array('module' => 'flickr','controller' => 'photos','action' => 'inaset','id'=> $d['id']),'default',true);?>" title="View photos on our site">View all photos here</a></p>
</div>
<?php endforeach;?>
</div>
<?php echo $this->paginationControl($this->data, 'Sliding', 'structure/pagination.phtml'); ?>

<?php else:?>
<p>There are no sets available at the moment</p>
<?php endif;?>