<?php 
$site = Zend_Registry::get('siteurl');
$module = Zend_Controller_Front::getInstance()->getRequest()->getModuleName();	
$controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();	
$action = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
$contextSwitch = Zend_Controller_Action_HelperBroker::getStaticHelper('ContextSwitch');	
$param = Zend_Controller_Front::getInstance()->getRequest()->getParam('id');
$contexts = $contextSwitch->getContexts();

$dom 	  = new DomDocument("1.0", "UTF-8");
$projects  = $dom->createElement('response');
$meta = $dom->createElement('meta');
$projects->appendChild($meta);
$meta->appendChild( $dom->createElement('generated', date(DATE_W3C,time())));
$meta->appendChild( $dom->createElement('totalItems',$this->data['total']));
$meta->appendChild( $dom->createElement('currentPage',$this->data['pageNumber']));
$meta->appendChild( $dom->createElement('totalPages',$this->data['totalPages']));
$meta->appendChild( $dom->createElement('itemsReturned',$this->data['itemsReturned']));
$formats = $dom->createElement('formats');
$meta->appendChild($formats);	
foreach ($contexts as $k => $v){
$formats->appendChild( $dom->createElement($k, $site . $this->url(array('module' => $module,
'controller' => $controller,'action' => $action,'id' => $param,'format' => $k),NULL,true)  ));
}
$formats->appendChild( $dom->createElement('html', $site . $this->url(array('module' => $module,
'controller' => $controller,'action' => $action,'id' => $param),NULL,true)  ));

$projectsElem = $dom->createElement('projects');
// set it's attribute
$projects->appendChild( $projectsElem );
foreach($this->projects as $r){
	$projectElem = $dom->createElement('project');
 foreach($r as $k => $a){
       $projectElem->appendChild( $dom->createElement($k, htmlspecialchars($a))); 
   }
$projectsElem->appendChild( $projectElem );
}

$dom->appendChild( $projects );

$xmlData  = $dom->saveXML();
echo $xmlData;
