<?php 
$this->headTitle('Coroner\'s of England and Wales mapped');
$this->metaBase('A map of the locations for coroners known to the  Portable Antiquities Scheme','Coroners map',
'map,google,contacts,scheme,coroners,archaeology,deaths');

$this->inlineScript()->appendFile('http://maps.google.com/maps/api/js?sensor=false',$type='text/javascript');
?>
<h2>Map of coroners locations</h2>
<?php $this->inlineScript()->captureStart() ?>
 $(document).ready(function() {
  var center = new google.maps.LatLng(54.70235509327093, -3.2080078125);
  var myOptions = {
    zoom: 6,
    center: center,
    mapTypeId: google.maps.MapTypeId.SATELLITE
  }

  var map = new google.maps.Map(document.getElementById("map"), myOptions);

  var Layer = new google.maps.KmlLayer('<?php echo 'http://finds.org.uk' . $this->url(array('module' => 'contacts','controller' => 
  'coroners','action' => 'index','format' => 'kml'),'default',true);?>');
  Layer.setMap(map);
  });
<?php $this->inlineScript()->captureEnd() ?>
<div id="map" style="width:95%; height:800px;"> 
<div id="loading"></div>
</div>