<?php
$this->jQuery()->addJavascriptFile($this->baseUrl() . '/js/JQuery/jquery.lightbox.js',
$type='text/javascript');  
echo $this->partialLoop('partials/content/article.phtml',$this->content);
?>
<?php $this->jQuery()->javascriptCaptureStart(); ?>
jQuery(document).ready(function($) {
$('a[rel*=lightbox]').lightBox() 
});
<?php $this->jQuery()->javascriptCaptureEnd(); ?>
<?php echo $this->latestRecords('objectType:coin broadperiod:"IRON AGE"');?>
