<li><a href="<?php echo $this->url(array('module' => 'database','controller' => 'search','action' => 'results','rallyID' => $this->rallyID,'createdby' => $this->id),null,true);?>" title="Find all records recorded at this rally by <?php echo $this->fullname;?>"><?php echo $this->fullname;?></a>

<?php if(isset($this->datefrom)):?>
 Attended: <?php if(isset($this->datefrom)){ echo $this->niceshortdate($this->datefrom);}?><?php if(isset($this->dateto)) { echo ' - '. $this->niceshortdate($this->dateto);}?> 
 <?php endif;?>
   <?php 
echo $this->Href(array('module' => 'database','controller'=>'rallies', 'action'=>'deleteflo', 'checkAcl'=>true,
'acl'=>'Zend_Acl',  'params' =>array('rallyID'=>$this->rallyID,'staffID' => $this->id), 'content'=>'Delete','attribs' => array('title' => 'Delete flo details from this rally')));
?> </li>
 
