<h4>Coin data (numismatics)</h4>
<?php echo $this->CoinEditDeleteLink($this->old_findID,$this->id,$this->broadperiod,
$this->secuid,$this->returnID,$this->createdBy);?>

<p>
<?php if($this->d != NULL):?>
Denomination: <?php echo $this->escape($this->d);?> <span class="scope">[<a href="<?php echo $this->url(array('module' => 'byzantinecoins','controller'=>'denominations','action'=>'denomination','id' => $this->denom),null,true);?>" title="Read scope note for <?php echo $this->d;?>">scope notes</a> | <a href="<?php echo $this->url(array('module' => 'database','controller' => 'search','action'=>'results','denomination' => $this->denom),null,true);?>" title="view all records assigned to denomination: <?php echo $this->d;?>">View all attributed records</a>]</span><br />
<?php endif;?>
<?php if($this->ruler1 != NULL):?>
Ruler/issuer: <?php echo $this->escape($this->ruler1);?> <span class="scope">[<a href="<?php echo $this->url(array('module' => 'byzantinecoins','controller'=>'rulers','action'=>'ruler','id' => $this->ruler_id),null,true);?>" title="Read scope note for <?php echo $this->period_name;?>">scope notes</a> | <a href="<?php echo $this->url(array('module' => 'database','controller'=>'search','action'=>'results','ruler' => $this->ruler_id),null,true);?>" title="view all records assigned to <?php echo $this->ruler1;?>">View all attributed records</a>]</span><br />
<?php endif;?>
<?php if($this->ruler2 != NULL):?>
Secondary ruler/issuer: <?php echo $this->escape($this->ruler2);?> <span class="scope">[<a href="<?php echo $this->url(array('module' => 'byzantinecoins','controller'=>'rulers','action'=>'ruler2_id','id' => $this->ruler2_id),null,true);?>" title="Read scope note for <?php echo $this->period_name;?>">scope notes</a> | <a href="<?php echo $this->url(array('module' => 'database','controller'=>'search','action'=>'results','ruler' => $this->ruler2_id),null,true);?>" title="view all records assigned to <?php echo $this->ruler2;?>">View all attributed records</a>]</span><br />
<?php endif;?>
<?php if($this->mint_name != NULL):?>
Mint or issue place: <?php echo $this->escape($this->mint_name);?><br />
<?php endif;?>
<?php if($this->obverse_description != NULL):?>
Obverse description: <?php echo $this->obverse_description;?><br />
<?php endif;?>
<?php if($this->obverse_inscription != NULL):?>
Obverse inscription: <?php echo $this->obverse_inscription;?><br />
<?php endif;?>
<?php if($this->reverse_description != NULL):?>
Reverse description: <?php echo $this->reverse_description;?><br />
<?php endif;?>
<?php if($this->reverse_inscription != NULL):?>
Reverse inscription: <?php echo $this->reverse_inscription;?><br />
<?php endif;?>
<?php if($this->die_axis_name != NULL):?>
Die axis measurement: <?php echo $this->escape($this->die_axis_name);?><br />
<?php endif;?>
<?php if($this->wear != NULL):?>
Degree of wear: <?php echo $this->escape($this->wear);?>
<?php endif;?>
</p>
