<tr>
<td><a href="<?php echo $this->url(array('module' => 'database','controller' => 'osdata','action' => 'oneto50k','id' => $this->id),NULL,true);?>" title="View details for 1:50K record - <?php echo $this->escape($this->monumentName);?>"><?php echo $this->escape($this->monumentName);?></a></td>
<td><?php echo $this->county;?></td>
<td><?php 
if($this->f_code == 'R') {
echo 'Roman Antiquity';
} else if($this->f_code == 'A'){
echo 'Antiquity';	
}
?>
</td>
<td></td>
<td><?php echo $this->gridref;?></td>
</tr>