<tr>
<td><a href="<?php echo $this->url(array('module' => 'database','controller' => 'people','action' => 'person','id' => $this->id),null,true);?>" title="View <?php echo $this->forename;?> <?php echo $this->surname;?>'s details"><?php echo $this->forename;?> <?php echo $this->surname;?></a> 
</td>
<td><?php echo $this->county;?></td>
<td><?php echo $this->org;?>
<td><?php echo $this->role;?></td>
<td>[<a href="<?php echo $this->url(array('module' => 'database','controller' => 'people','action' => 'edit','id' => $this->id),null,true);?>" title="Edit <?php echo $this->forename;?> <?php echo $this->surname;?>">Edit</a> | <a href="<?php echo $this->url(array('module' => 'database','controller' => 'people','action' => 'delete','id' => $this->id),null,true);?>" title="Delete <?php echo $this->forename;?> <?php echo $this->surname;?>">Delete</a>] </td>
</tr>