<p>
<?php 
if(isset($this->finderID)) {
$auth = Zend_Registry::get('auth');
if($auth->hasIdentity()){
$user = $auth->getIdentity();
{
$allowed = array('fa','admin','flos','hero','research');
if(in_array($user->role,$allowed)){ 
?>
Found by: <span property="pas:finder" ><?php echo $this->escape($this->tit1);?> <?php echo $this->escape($this->fore);?> 
<?php echo $this->escape($this->sur);?></span> - <span class="scope">[<a href="
<?php echo $this->url(array('module' => 'database','controller' => 'ajax',
'action' => 'otherdiscoveries', 'id' => $this->secuid),null,true);?>" title="View other discoveries" 
rel="facebox">view other discoveries by this finder</a>]</span><br />
<?php
}
}
} else {
	?>
Found by: This information is restricted for your login. <br />
<?php 
}
}
?>

<?php if(isset($this->recorderID)) : ?> 
Recorded by: <span property="pas:recorder foaf:name"><?php echo $this->escape($this->tit3);?> <?php echo $this->escape($this->fore3);?> <?php echo $this->escape($this->sur3);?></span> 
- <span class="scope">[ 
<a href="<?php echo $this->url(array('module' => 'database','controller' => 'search','action' => 'results','recorderID' => $this->recorderID),null,true);?>" title="Search database for all records recorded by <?php echo $this->escape($this->tit3);?> <?php echo $this->escape($this->fore3);?> <?php echo $this->escape($this->sur3);?>">view all attributed records</a>]</span><br />
<?php endif;?>

<?php if($this->identifier1ID != NULL) :?>
Identified by: <span property="pas:identifier foaf:name" ><?php echo $this->escape($this->tit2);?> <?php echo $this->escape($this->fore2);?> <?php echo $this->escape($this->sur2);?></span> - <span class="scope">[<a href="<?php echo $this->url(array('module' => 'database','controller' => 'search','action' => 'results','idby' => $this->identifier1ID),null,true);?>" title="Search database for all records identified by <?php echo $this->escape($this->tit2);?> <?php echo $this->escape($this->fore2);?> <?php echo $this->escape($this->sur2);?>">view all attributed records</a>]</span><br />
<?php endif;?>

<?php if($this->identifier2ID != NULL) :?>
Secondary identifier: <span property="pas:identifierSecondary foaf:name" instanceof="foaf:person"><?php echo $this->escape($this->tit5);?> <?php echo $this->escape($this->fore5);?> <?php echo $this->escape($this->sur5);?></span> - <span class="scope">[<a href="<?php echo $this->url(array('module' => 'database','controller' => 'search','action' => 'results','idby2' => $this->identifier1ID),null,true);?>" title="Search database for all records identifed by <?php echo $this->escape($this->tit5);?> <?php echo $this->escape($this->fore5);?> <?php echo $this->escape($this->sur5);?>">view all attributed records</a>]</span><br />
<?php endif;?>
</p>
