<h4>Coin data (numismatics)</h4>
<?php echo $this->CoinEditDeleteLink($this->old_findID,$this->id,$this->broadperiod,$this->secuid,$this->returnID,$this->createdBy);?>

<p>
<?php if($this->d != NULL) : ?>
Denomination: <?php echo $this->escape($this->d);?> <span class="scope">[<a href="<?php echo $this->url(array('module'=>'postmedievalcoins','controller' => 'denominations','action'=>'denomination','id' => $this->denom),null,true);?>" title="Read scope note for <?php echo $this->d;?>">scope notes</a> |  <a href="<?php echo $this->url(array('module' => 'database','controller'=>'search','action'=>'results','denomination' => $this->denom),null,true);?>" title="view all records assigned to denomination: <?php echo $this->d;?>">view all attributed records</a>]</span><br />
<?php endif;?>

<?php if($this->ruler1 != NULL) : ?>
Ruler/issuer: <?php echo $this->escape($this->ruler1);?> <span class="scope">[<a href="<?php echo $this->url(array('module'=>'postmedievalcoins','controller' => 'rulers','action'=>'ruler','id' => $this->ruler_id),null,true);?>" title="Read scope note for <?php echo $this->ruler1;?>">scope notes</a> | <a href="<?php echo $this->url(array('module' => 'database','controller' => 'search','action'=>'results','ruler' => $this->ruler_id),null,true);?>" title="view all records assigned to <?php echo $this->ruler1;?>">View all attributed records</a>]</span><br />
<?php endif;?> 

<?php if($this->mint_name != NULL) : ?>
Mint or issue place: <?php echo $this->escape($this->mint_name);?> <span class="scope">[<a href="<?php echo $this->url(array('module'=>'postmedievalcoins','controller' => 'mints','action'=>'mint','id' => $this->mint_id),null,true);?>" title="Read scope note for <?php echo $this->mint_name;?>">scope notes</a> | <a href="<?php echo $this->url(array('module' => 'database','controller'=>'search','action'=>'results','mint' => $this->mint_id),null,true);?>" title="view all records assigned to <?php echo $this->mint_name;?>">View all attributed records</a>]</span><br />
<?php endif;?>

<?php if($this->category != NULL) : ?>
Category: <?php echo $this->escape($this->category);?> <span class="scope">[<a href="<?php echo $this->url(array('module'=>'postmedievalcoins','controller' => 'categories','action'=>'category','id' => $this->categoryID),null,true);?>" title="Read scope note for <?php echo $this->category;?>">scope notes</a> | <a href="<?php echo $this->url(array('module'=>'database','controller' => 'search','action'=>'results','category' => $this->categoryID),null,true);?>" title="view all records assigned to <?php echo $this->category;?>">View all attributed records</a>]</span><br />
<?php endif;?>


<?php if($this->type != NULL) : ?>
Type: <?php echo $this->escape($this->type);?> <span class="scope">[<a href="<?php echo $this->url(array('module'=>'postmedievalcoins','controller' => 'types','action'=>'type','id' => $this->typeID),null,true);?>" title="Read scope note for <?php echo $this->type;?>">scope notes</a> | <a href="<?php echo $this->url(array('module' => 'database','controller'=>'search','action'=>'results','typeID' => $this->typeID),null,true);?>" title="view all records assigned to <?php echo $this->type;?>">View all attributed records</a>]</span><br />
<?php endif;?>

<?php if($this->obverse_description != NULL) : ?>
Obverse description: <?php echo $this->obverse_description;?><br />
<?php endif;?>

<?php if($this->obverse_inscription != NULL) : ?>
Obverse inscription: <?php echo $this->obverse_inscription;?><br />
<?php endif;?>

<?php if($this->reverse_description != NULL ) : ?>
Reverse description: <?php echo $this->reverse_description;?><br />
<?php endif;?>

<?php if($this->reverse_inscription != NULL) : ?>
Reverse inscription: <?php echo $this->reverse_inscription;?><br />
<?php endif;?>

<?php if($this->reverse_mintmark != NULL) :?>
Reverse mintmark: <?php echo $this->escape($this->reverse_mintmark);?><br />
<?php endif;?>

<?php if($this->initial_mark != NULL) :?>
Initial mark: <?php echo $this->escape($this->initial_mark);?><br />
<?php endif;?>

<?php if($this->die_axis_name != NULL) : ?>
Die axis measurement: <?php echo $this->escape($this->die_axis_name);?> <span class="scope">[<a href="<?php echo $this->url(array('module' => 'database','controller'=>'terminology','action'=>'dieaxis','id' => $this->die),null,true);?>" title="Read scope note for <?php echo $this->die_axis_name;?>">scope notes</a> | <a href="<?php echo $this->url(array('module' => 'database','controller'=>'search','action'=>'results','axis' => $this->die),null,true);?>" title="view all records assigned to <?php echo $this->die_axis_name;?>">View all attributed records</a>]</span><br />
<?php endif;?>

<?php if($this->wear != NULL) : ?>
Degree of wear: <?php echo $this->escape($this->wear);?> <span class="scope">[<a href="<?php echo $this->url(array('module' => 'database','controller'=>'terminology','action'=>'weartype','id' => $this->wearID),null,true);?>" title="Read scope note for <?php echo $this->wear;?>">scope notes</a> | <a href="<?php echo $this->url(array('module' => 'database','controller'=>'search','action'=>'results','wear' => $this->wearID),null,true);?>" title="view all records assigned to <?php echo $this->wear;?>">View all attributed records</a>]</span>
<?php endif;?>
</p>
