<?php 
$this->headTitle('Details for '. $this->escape($this->ellipsisstring($this->title,90)));
$this->headMeta('','dc.Keywords');
$this->headMeta('The Portable Antiquities Scheme and the British Museum','dc.Publisher');
$this->headMeta('Details for reference work '.$this->title,'dc.Description');
$this->headMeta($this->c,'dc.date.created');
$this->headMeta('Archaeology','dc.subject');
?>
<div about="<?php echo $this->CurUrl();?>" typeof="bibo:AcademicArticle">
<h2>Publication details</h2>

<ul>
<li>Full title: <span property="dc:title"><?php echo $this->escape($this->title);?></span></li>
<?php if(!is_null($this->authors)):?>
<li>Author or editor: <?php echo $this->escape($this->authors);?></li>
<?php endif;?>
<?php if(!is_null($this->publication_place)):?>
<li>Publication place: <?php echo $this->escape($this->publication_place);?></li>
<?php endif;?>
<?php if(!is_null($this->publisher)):?>
<li>Publisher: <?php echo $this->escape($this->publisher);?></li>
<?php endif;?>
<?php if(!is_null($this->publication_year)):?>
<li>Published: <?php echo $this->escape($this->publication_year);?></li>
<?php endif;?>
<?php if(!is_null($this->t)):?>
<li>Publication type: <?php echo $this->escape($this->t);?></li>
<?php endif;?>
<?php if(!is_null($this->ISBN)):?>
<li>ISBN number: <span property="bibo:isbn10"><?php echo $this->escape($this->ISBN);?></li>
<?php endif;?>
<li>This was created by: <?php echo $this->escape($this->fn);?> on the: <?php echo $this->escape($this->c);?></li>
<?php if(!is_null($this->u)):?>
<li>Record last updated by: <?php echo $this->escape($this->fn2);?> on the <?php echo $this->escape($this->u);?></li>
<?php endif;?>
</ul>
<?php
$auth = Zend_Auth::getInstance();
if($auth->hasIdentity())
{
$user = $auth->getIdentity();
{
$allowed = array('fa','admin','flos');
if(in_array($user->role,$allowed))
{
echo '<p><a href="'. 
$this->url(array('module' => 'database','controller'=>'publications','action'=>'edit', 'id'=>$this->id),null,true)
.'" title="Edit this publication">Edit</a> | <a href="'.
$this->url(array('module' => 'database','controller'=>'publications','action'=>'delete', 'id'=>$this->id),null,true)
.'" title="Delete this publication">Delete</a></p>';
}
}
}
;?>
</div>
<?php if($this->ISBN > 0) {


$config = Zend_Registry::get('config');
$cache = Zend_Registry::get('cache');
$amazonKey = $config->webservice->amazon->apikey;
$amazonSecret = $config->webservice->amazon->secretkey;
$amazonCountry = $config->webservice->amazon->country;
$amazon = new Zend_Service_Amazon($amazonKey,$amazonCountry,$amazonSecret);
$book = $amazon->itemLookup($this->ISBN,array('AssociateTag' => 'portaantiqsch-20', 'ResponseGroup' => 'Large'));


//Zend_Debug::dump($book);
echo '<div><p>';
if(array_key_exists('MediumImage',$book) && ($book->MediumImage != NULL))
{
echo '<img src="'.$book->MediumImage->Url.'" alt="Cover image for '.$book->Title.'" height="'.$book->MediumImage->Height.'" width="'.$book->MediumImage->Width.'" class="amazonpicture" />';
}

echo '<a href="'.$book->DetailPageURL . '" title="View full details at Amazon"> ' . $book->Title. '</a> <br /> ';
echo 'Number of pages: '. $book->NumberOfPages.'<br />';
echo 'Total new copies available: '.$book->Offers->TotalNew . '<br />';
echo 'Total used copies available: '.$book->Offers->TotalUsed . '<br />';
if(array_key_exists('FormattedPrice',$book))
	{
echo 'Price for new copy: ' .$book->FormattedPrice.'<br />';
	}
echo 'Current sales rank at Amazon: ' . $book->SalesRank.'<br />';
echo 'Binding type: ' . $book->Binding. '<br />';
echo 'Publisher: ' . $book->Publisher. '<br />';
echo 'Original publication date: ' . $this->niceshortdate($book->PublicationDate).'<br />';
if(array_key_exists('Author',$book) && ($book->Author > 0))
{
echo 'Authors: ';
foreach ($book->Author AS $author) {
   echo "{$author}<br />";
}
}
echo '</p>';

if($book->SimilarProducts > 0){
echo '<h3>Similar books</h3>';
echo '<ul>';
foreach ($book->SimilarProducts AS $sim) {
echo "<li>{$sim->Title}</li>";
}
}
echo '</ul>';

echo '</div>';
}
?>