<?php
$action = $this->term;
switch ($action) {
		case $action == strtoupper('Roman'):
			$actionset = 'emperor';
			$module = 'romancoins';
			break;
		case $action == strtoupper('Byzantine'):
			$module = 'byzantinecoins';
			$actionset = 'ruler';
			break;
		case $action == strtoupper('Greek and Roman Provincial');
			$module = 'greekromancoins';
			$actionset = 'ruler';
			break;
		case $action == strtoupper('Post Medieval'):
			$module = 'postmedievalcoins';
			$actionset = 'ruler';
			break;
		case $action == strtoupper('Early Medieval'):
			$module = 'earlymedievalcoins';
			$actionset = 'ruler';
			break;
		case $action == strtoupper('Iron Age'):
			$module = 'ironagecoins';
			$actionset = 'ruler';
			break;
		case $action == strtoupper('medieval');
			$module = 'medievalcoins';
			$actionset = 'ruler';
			break;
			default:
			$actionset = 'ruler';
			$module = 'medievalcoins';
	}
	
	
	?>
<tr>
<td><a href="<?php echo $this->url(array('module' => $module,'controller' => $actionset.'s' ,'action' => $actionset,'id' => $this->id),null,true);?>"><?php echo $this->issuer;?></a></td>
<td><a href="<?php echo $this->url(array('module' => 'database','controller' => 'terminology','action' => 'period','id' => $this->i),null,true);?>"><?php echo $this->term;?></a></td>
<td><?php echo $this->ADBC($this->date1) . ' ' . $this->ADBC($this->date2);?></td> 
</tr>
