<tr>
<td><a href="<?php echo $this->url(array('module' => 'database','controller' => 'smr','action' => 'record','id' => $this->id),NULL,true);?>" title="View details for SMR - <?php echo $this->escape($this->monumentName);?>"><?php echo $this->escape($this->monumentName);?></a></td>
<td><?php echo $this->county;?></td>
<td><?php echo $this->district;?></td>
<td><?php echo $this->parish;?></td>
<td><?php echo $this->gridref;?></td>
</tr>