<?php $module = Zend_Controller_Front::getInstance()->getRequest()->getModuleName();?>

<h4>Spatial data</h4> 

<p>
<?php if($this->region != NULL) :?>
Region: <?php echo $this->escape(ucwords(strtolower($this->region)));?><br />
<?php endif;?>
<?php if($this->county != NULL) :?>
County: <?php echo $this->escape(ucwords(strtolower($this->county)));?><br />
<?php endif;?>
<?php if($this->district != NULL) :?>
District: <?php echo $this->escape(ucwords(strtolower($this->district)));?><br />
<?php endif;?>
	
<?php
if(($this->parish != NULL) && (empty($this->knownas)))
{
echo 'Parish: '. ucwords(strtolower($this->parish)).'<br />';
?>
<?php if($this->knownas != NULL) :?>
<span class="knownas">To be known as: <?php echo $this->escape($this->knownas);?></span>
<?php endif;?>
<?php
}
?>
<?php
 if(($this->gridref != NULL) && (empty($this->knownas))) {
 ?>
<p>
Restricted 4 Figure grid reference:  <span class="fourfigure"><?php echo $this->fourFigure;?></span><br>
<?php 
echo 'Grid reference source: '.$this->escape($this->source).'<br />
Grid reference accurate to a '.$this->GetAccuracy($this->gridref).' metre square.</p>';
}
?>
<p>
<?php if($this->method != NULL) :?>
Method of discovery: <?php echo $this->escape($this->method);?>
 <span class="scope">[<a href="<?php echo $this->url(array('module' => $module,'controller'=>'terminology',
'action'=>'method','id' => $this->discmethod),null,true);?>"
 title="Read scope note for <?php echo $this->method;?>">scope notes</a> | <a href="
 <?php echo $this->url(array('module' => $module,'controller'=>'search','action'=>'results','discmethod' => $this->discmethod),null,true);?>" title="view all records assigned to <?php echo $this->method;?>">view all attributed records</a>]</span><br />
<?php endif;?>
<?php if($this->disccircum != NULL) :?>
Discovery circumstances:  <?php echo $this->escape($this->disccircum);?> <br />
<?php endif;?>
<?php if($this->curr_loc != NULL) :?>
Current location: <?php echo $this->escape($this->curr_loc);?> <br /> 
<?php endif;?>
<?php if($this->landvalue != NULL) :?>
General landuse: <?php echo $this->landvalue;?> <span class="scope">[<a href="<?php echo $this->url(array('module' => $module,'controller' => 'terminology','action' => 'landuse','id' => $this->landusevalue),Null, true);?>" title="View scope notes for <?php echo $this->landvalue;?>">scope notes</a> | <a href="<?php echo $this->url(array('module' => $module,'controller' => 'search','action' => 'results','value' => $this->landusevalue),Null, true);?>" title="View all records assigned to <?php echo $this->landvalue;?>">view all attributed records</a></span><br>
<?php endif;?>
<?php if(isset($this->landuse)) :?>
Specific landuse: <?php echo $this->escape($this->landuse);?> <span class="scope">[<a href="<?php echo $this->url(array('module' => $module,'controller'=>'terminology','action'=> 'landuse','id' => $this->landusecode),null,true);?>" title="Read scope note for <?php echo $this->landuse;?>">scope notes</a> | <a href="<?php echo $this->url(array('module' => $module, 'controller' => 'search','action' => 'results','landuse' => $this->landusecode),Null, true);?>" title="View all records assigned to <?php echo $this->landusecodee;?>">view all attributed records</a>]</span><br/>
<?php endif;?>
</p>