<?php 
$date = Zend_Date::now();
?>

<?php echo  $this->sur3. ', ' . substr($this->fore3,0,1) .' ('. $this->c .') <em>'.$this->old_findID.' A ' .$this->broadperiod.' '.$this->objecttype. ' </em>Webpage available at: <a href="http://'.$_SERVER['SERVER_NAME']
 .$this->url(array('module' => 'database','controller' => 'artefacts','action' => 'record','id' => $this->id),null,true).'">http://'. $_SERVER['SERVER_NAME']
 .$this->url(array('module' => 'database','controller' => 'artefacts','action' => 'record','id' => $this->id),null,true).'</a> [Accessed: ' . $date.']';
?>
<form action="" method="get">
<textarea name="" cols="100%" rows="5"><?php echo  $this->sur3. ',' . substr($this->fore3,0,1) .' ('. $this->c .') '.$this->old_findID.' A ' .$this->broadperiod.' '.$this->objecttype. ' Webpage available at: http://'. $_SERVER['SERVER_NAME']
 .$this->url(array('module' => 'database','controller' => 'artefacts','action' => 'record','id' => $this->id),null,true).' [Accessed: ' . $date.']';
?></textarea>
</form>
