<?php 
$this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/jQueryLinkedSelect.js',$type='text/javascript'); 
$this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/coinslinkedselect.js',$type='text/javascript'); 
$this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/linkedinit.js',$type='text/javascript');
$this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/iacoinslinkedinit.js',$type='text/javascript');
$this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/jquery.autocomplete.pack.js',$type='text/javascript');
$this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/autocompleteinit.js',$type='text/javascript'); 
$this->headLink()->appendStylesheet($this->baseUrl().'/css/autocomplete.css')
->appendStylesheet($this->baseUrl().'/css/ui.datepicker.css');
$this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/ui.datepicker.js',$type='text/javascript'); 
$this->headTitle('Advanced search the database');

?>


<?php $this->jQuery()->javascriptCaptureStart() ?>
$(document).ready(function() {
$("#createdBefore").datepicker({ maxDate: '+1y'});
$("#createdAfter").datepicker({ maxDate: '+1y' });


	
});
<?php $this->jQuery()->javascriptCaptureEnd() ?>

<h2>Advanced search</h2>
<p>This form allows you to perform some more advanced database searches. More specific numismatic searching can be affected from period specific forms.</p>
<?php
 echo $this->form;
?>
