<?php 
$this->headMeta('The Greek and Roman provincial coins that the Scheme has 
    recorded (of which there are few) can be searched using this form','description');
$this->headMeta('greek,roman,coins,numismatics,provinicial,search,england,wales,
    portable antiquituies','dc.keywords');
$this->headTitle('Greek &amp; Roman Provincial numismatic search');
?>
<h2>Greek and Roman provincial coin search</h2>
<?php echo $this->form;?>