<h2>Search results from Solr</h2>

<?php if ($this->results): ?>

<p><a href="/database/search/solr/">Back to search</a></p>
<h3>Facets available</h3>
<?php if($this->facetlistObject):?>
<div style="float:left; width:180px;">
<h4>Object types</h4>
<ul >
<?php foreach($this->facetlistObject as $k => $v):?>
<li><?php echo $k;?> <?php echo $v;?></li>
<?php endforeach;?>
</ul>
</div>
<?php endif;?>
<?php if($this->facetlistPeriod):?>
<div style="float:left; width:180px;" >
<h4>Broad period</h4>
<ul>
<?php foreach($this->facetlistPeriod as $k => $v):?>
<li><?php echo $k;?> <?php echo $v;?></li>
<?php endforeach;?>
</ul>
</div>
<?php endif;?>

<?php if($this->facetlistMaterial):?>
<div style="float:left; width:180px;">
<h4>Material</h4>
<ul>
<?php foreach($this->facetlistMaterial as $k => $v):?>
<li><?php echo $k;?> (<?php echo $v;?>)</li>
<?php endforeach;?>
</ul>
</div>
<?php endif;?>

<?php if($this->facetlistCounties):?>
<div style="float:left; width:180px;">
<h4>County</h4>
<ul>
<?php foreach($this->facetlistCounties as $k => $v):?>
<li><?php echo $k;?> (<?php echo $v;?>)</li>
<?php endforeach;?>
</ul>
</div>
<?php endif;?>


<table class="stripeMe" summary="Table of your search results">
<caption>Your search results</caption>
<thead>
  <tr> 
  	<th>Image</th>
    <th>Object Type</th>
    <th>Find number</th>
    <th>Broadperiod</th>
    <th>County</th>
	<th>Actions</th>
  </tr>
 </thead>
 <tbody>
<?php echo $this->partialLoop('partials/database/findsTable2.phtml',$this->results);?>
  </tbody>
</table>

<?php else :?>
<?php echo '<p>Your search has produced no results. Please refine your query. If you are expecting more results, you may have insufficient access for their workflow stage.</p>';?>
<?php endif; ?>


<?= $this->paginationControl($this->paginator, 'Sliding', 'structure/queryPagination.phtml'); 
$this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/jquery.lightbox.js',$type='text/javascript'); 
?>
<?php $this->jQuery()->javascriptCaptureStart() ?>
jQuery(document).ready(function($) {

 $('a[rel*=lightbox]').lightBox() 
    });
<?php $this->jQuery()->javascriptCaptureEnd() ?>