<tr>
<td><a href="
<?php echo $this->url(array('module' => 'database','controller' => 'search','action' => 'results','createdby' => $this->id,'createdAfter' => $this->datefrom,'createdBefore' => $this->dateto),'default',true);?>" title="Find all records created by <?php echo $this->fullname;?> on these dates"><?php echo $this->fullname;?></a></td>
<td><?php echo $this->institution;?></td>
<td><?php echo $this->finds;?></td>
<td><?php echo $this->records;?></td>
</tr>