<?php 
	$this->headTitle('Edit Medieval coin type: ');
$this->headScript()->prependFile($this->baseUrl().'/js/JQuery/jquery-1.2.3.min.js',$type='text/javascript'); ?>
<?php $this->headScript()->appendFile($this->baseUrl().'/js/JQuery/jquery.menu.js',$type='text/javascript'); ?>


<?php $this->headLink()->appendStylesheet($this->baseUrl().'/css/menu.css')
->appendStylesheet($this->baseUrl().'/css/style.css')
->appendStylesheet($this->baseUrl().'/css/default.css');?>

<h2>Add a new object</h2>

<?php 
echo $this->form;
?>