<h2>Reece periods</h2>
<p><a href="<?php echo $this->url(array('module' => 'admin','controller'=>'numismatics','action'=>'addreeceperiod'),null,true);?>">Add a Reece Period</a></p>

<table class="stripeMe" summary="A list of all Reece periods used on the database">
<thead>
<tr>
<th>Reece period</th>
<th>Created</th>
<th>Created by</th>
<th>Updated</th>
<th>Updated by</th>
<th>Actions</th>
</tr>
</thead>
<tbody>
<?php echo $this->partialLoop('partials/admin/reeces.phtml', $this->reeces) ?>
</tbody>
</table>
