<h2>Medieval types registered on database</h2>
<p><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'numismatics','action' => 'addtype'),null,true);?>" title="Add a new medieval type">Add a new type</a></p>
<?php if (count($this->paginator)): ?>

<table class="stripeMe" summary="List of all active medieval coin types">
<thead>
<tr>
<th>Type name</th>
<th>Created</th>
<th>Created by</th>
<th>Updated</th>
<th>Updated by</th>
<th>Actions</th>
</tr>
<thead>
<tbody>
<?php echo $this->partialLoop('partials/admin/types.phtml',$this->paginator);?></tbody>
</table>
<?php else:?>
<p>You have either entered an incorrect url parameter, or there are no recorded coin types available.</p>
<?php endif; ?>

<?echo $this->paginationControl($this->paginator, 'Sliding', 'structure/pagination.phtml'); ?>
