<div id="researchtable">
<table class="stripeMe" summary="Breakdown of research being conducted on Scheme data">
<caption>Research project types</caption>
<thead>
<tr>
<th>Level of research</th>
<th>Number</th>
</tr>
</thead>
<tfoot>
<tr>
<td>Total projects:</td>
<td><?php $quant = array();foreach($this->research as $r) {
$quant[] = $r['quantity'];
}
echo array_sum($quant);?></td>
</tr>
</tfoot>
<tbody>
<?php echo $this->partialLoop('partials/research/types.phtml',$this->research);?>
</tbody>
</table>
</div>
<?php echo $this->partialLoop('partials/content/article.phtml',$this->contents);?>
