<?php
$type = '.jpg';
$url = 'http://farm'. $c->iconfarm . '.static.flickr.com/' . $c->iconserver . '/buddyicons/' . $c->nsid . $type;
$alturl = 'http://www.flickr.com/images/buddyicon.jpg';
$link = $this->url(array('module' => 'flickr','controller' => 'contacts','action' => 'known','as' => $c->username),'default',true);
if($c->iconfarm != 0) {
echo '<a href="' . $link .'" title="Go to ' . $c->username . '\'s profile on flickr" rel="friend"><img src="' 
. $url . '" height="48" width="48" alt="View ' 
. $c->username . '\'s images" /></a>';
} else {
echo '<a href="' . $link . '" title="View this ' . $c->username . '\'s profile " rel="friend"><img src="' . $alturl 
. '" height="48" width="48" alt="View ' 
. $c->username . '\'s images" /></a>';
}
