<div class="hnews hentry item">
<h3><a class="url entry-title" rel="bookmark" href="<?php echo $this->url(array('module' => 'news','controller' => 'stories','action' => 'article','id' => $this->id),null,true);?>" title="Read this news story"><?php echo $this->title;?></a></h3>
<p><span class="updated dtstamp" title="<?php 
$date = strtotime($this->d);
echo date(DATE_ATOM,$date);?>">Published: <?php echo  $this->timeagoinwords($this->golive);?></span> </p>
<div class="entry-content"><?php echo $this->WordChars($this->contents);?></div>
<?php if(isset($this->latitude)):?>
<div class="geo forRDFOnly">
      Lat: <span class="latitude"><?php echo $this->latitude;?></span> 
      Long: <span class="longitude"><?php echo $this->longitude;?></span>
	  WOEID: <?php echo $this->woeid;?>
=  </div>
 <?php endif;?>
</div>
<?php echo $this->NewsCommentCount($this->id);?>