<?php 
$this->headTitle($this->title,'PREPEND');
$this->MetaBase(strip_tags($this->ellipsisstring($this->contents,150)),'archaeological news','');
?>
<h2><?php echo $this->title;?></h2>
<p>Date Published: <?php echo $this->timeagoinwords($this->golive);?>  
Author: <?php echo $this->escape($this->author);?></p>
<?php echo $this->contents;?>
<p>Contact: <?php echo $this->contactName;?> <a href="<?php echo $this->contactEmail;?>">
<?php echo $this->contactEmail;?></a> <?php echo $this->contactTel;?></p>
