Dear <?php echo $this->recipient;?>,

An error report has been submitted on <a href="http://www.finds.org.uk/database/artefacts/record/id/<?php echo $this->id;?>"><?php echo $this->findID;?></a>.
Object type: <?php echo $this->objecttype;?>
Broadperiod: <?php echo $this->broadperiod;?>

Type of report: <?php $this->errorType;?>

<?php echo $this->message;?>

Thank you for taking the time to submit an error to us, we will use this to improve our database.
