<?php if (count($this->tribes) > 0): ?>

<?php echo $this->partialLoop('partials/numismatics/tribe.phtml', $this->tribes) ;?>

<?php else: ?>
    <p class="error">There are no entries for this tribe.</p>
<?php endif; ?>

<?php if($this->images):?>
<h3>Latest examples recorded</h3>
<div id="latest">
<?php echo $this->partialLoop('partials/database/imagesPaged.phtml',$this->images);?>
</div>
<?php endif;?>
