
<li id="comment-<?php echo $this->id;?>" class="hentry u-<?php echo $this->comment_author;?>">
<span class="thumb vcard author">
<a class="tweet-url profile-pic url" href=""><?php echo $this->gravatar($this->comment_author_email,array(
	'imgSize' => 30, 'defaultImg' => 'monsterid', 'secure' => true),
	array('class' => 'avatar', 
    'title' => $this->comment_author . '\'s gravatar representation',
    'rating' => 'G'));
?>
</a>
</span>
<span class="status-body">
<strong>
<a class="tweet-url screen-name" title="Mike Heyworth" href="http://twitter.com/mikeheyworth"><?php echo $this->comment_author;?></a>
</strong> said: 
<span class="entry-content"><?php echo strip_tags($this->comment_content);?></span><br />
<span class="meta entry-meta">
<a class="entry-date" href="http://twitter.com/mikeheyworth/status/7479192534" rel="bookmark">
<span class="published timestamp" data="{time:'<?php echo $this->df;?>'}"><?php echo $this->df;?></span>
</a>
<span>
upon record: 
<a href="<?php echo $this->baseUrl();?>/database/artefacts/record/id/<?php echo $this->id;?>" title="View record"><?php echo $this->old_findID;?></a> a <?php echo $this->broadperiod . ' ' .$this->objecttype;?>
</span>
</span>

</span>
</li>
