<div class="thumbnail" id="thumbnail">
<a href="<?php echo $this->url(array('module' => 'users','controller' => 'named','action' => 'person','as' => urlencode($this->username)),null,true);?>" title="View <?php echo $this->escape($this->username);?>'s profile on our site">
<?php
echo $this->gravatar($this->email, array(
	'imgSize' => 90, 'defaultImg' => 'monsterid', 'secure' => true),
	array('class' => 'avatar', 
    'title' => $this->fullname . '\'s gravatar representation',
    'rating' => 'G'));

?>
</a>
<p>Username: <?php echo $this->escape($this->username);?><br />
Last visit: <?php echo $this->timeagoinwords($this->lastLogin);?><br />
Institution: <?php echo $this->institution;?>
</p>
</div>
