<?php $this->jQuery()->javascriptCaptureStart(); ?>
jQuery(document).ready(function($) {
$('a[rel*=lightbox]').lightBox() 
});
<?php 
$this->jQuery()->javascriptCaptureEnd();
$this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/jquery.lightbox.js',$type='text/javascript'); 
?>

<?php echo $this->partial('partials/database/objectTermData.phtml',$this->objectdata['0']);?>
<?php 

$term = $this->objectdata['0']['term'];
$this->headTitle('Explanation of object term '.$term);
?>
<?php echo $this->latestRecords('objectType:"' . $term . '"');?>

