<?php
$this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/facebox/facebox.js',$type='text/javascript');
$this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/facebox.init.js',$type='text/javascript');
$this->headLink()->appendStylesheet($this->baseUrl().'/js/JQuery/facebox/facebox.css')
->appendStylesheet($this->baseUrl().'/css/faceboxform.css');
?>

<?php echo $this->partialLoop('partials/database/periodDetails.phtml',$this->periods);?>
<h3>Object types recorded for this period</h3>
<ul>
<?php 
echo $this->partialLoop('partials/database/objectbyperiod.phtml',$this->objects);?>
</ul>
<p><a href="<?php echo $this->url(array('module' => 'database','controller' => 'ajax', 'action' => 'tagcloud', 'id' => $this->periods['0']['id']),null,true);?>" title="View a weighted tag cloud of object types" rel="facebox">View tag cloud of object types</a></p>
<?php echo $this->latestRecords('broadperiod:"' . $this->periods['0']['term'] . '"');?>