<?php echo $this->partialLoop('partials/numismatics/reeceDetail.phtml',$this->periods);?>

<h3>Issuers associated with this period</h3>
<ul id="related">
<?php echo $this->partialLoop('partials/numismatics/emperorList.phtml',$this->reeces);?>
</ul>

<?php if($this->reverses != NULL) :?>
<h3>Associated reverse types</h3>
<ul id="related">
<?php echo $this->partialLoop('partials/numismatics/revtypelistreece.phtml',$this->reverses);?>

</ul>
<?php endif;?>

<?php if($this->images):?>
<h3>Latest examples recorded</h3>
<div id="latest">
<?php echo $this->partialLoop('partials/database/imagesPaged.phtml',$this->images);?>
</div>
<?php endif;?>