<?php
$auth = Zend_Auth::getInstance();
if($auth->hasIdentity()) {
$user = $auth->getIdentity();
$allowed =  array('admin' , 'fa');
if(in_array($user->role,$allowed)) {
?>
<ul id="menu1" class="menu collapsible">
<li><a href="<?php echo $this->url(array('controller' => 'admin'),null,true);?>" title="Go to administration centre">Administration home</a></li>
<li><a href="#" title="Administer the contacts on the site">Contacts management</a>
<ul>
<li><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'contacts'),null,true);?>" title="Edit current staff">Current staff</a></li>
<li><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'coroners'),null,true);?>" title="Edit coroners">Coroners</a></li>
<li><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'contacts','action' => 'institutions'),null,true);?>" title="Edit institutions">Institutions</a></li>
<li><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'contacts','action' => 'roles'),null,true);?>" title="Edit staff roles">Staff roles</a></li>
</ul>
</li>
<li><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'news'),null,true);?>" title="Manage news listings">News management</a></li>

<li><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'research'),null,true);?>" title="Manage research listings">Research management</a></li>
<li><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'her'),null,true);?>" title="Manage the list of signed up HER officers">Manage HER sign ups</a></li>
<li><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'content'),null,true);?>" title="Go to content administration centre">Content management</a></li>
<li><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'quotes'),null,true);?>" title="Administer quotes and announcements">Quotes &amp; announcements</a></li>
<li><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'vacancies'),null,true);?>" title="Administer vacancies">Vacancies management</a></li>
<li><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'events'),null,true);?>" title="Go to events administration centre">Event management</a></li>
<li><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'numismatics'),null,true);?>" title="Administer the numismatic options">Numismatics</a></li>
<li><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'terminology'),null,true);?>" title="Administer controlled terms">Controlled terminology</a></li>

<li><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'users'),null,true);?>" title="Go to user administration centre">User admin</a></li>
<li><a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'system'),null,true);?>" title="Change system setup">System configuration</a></li>
<li><a href="#" title="Administer comments">Comments</a>
<ul>
<li><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'comments'),'default',true);?>" title="View all comments as one table">All comments</a></li>
<li><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'comments','approval' => 'spam'),'default',true);?>" title="View all comments as one table">Spam comments</a></li>
<li><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'comments','approval' => 'moderation'),'default',true);?>" title="View all comments as one table">Pending comments</a></li>
<li><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'comments','approval' => 'approved'),'default',true);?>" title="View all comments as one table">Authorised comments</a></li>
</ul>
</li>
</ul>
<?php
}
}
?>