<ul id="menu1" class="menu collapsible expandfirst">
<li><a href="#">Byzantine coins</a>
<ul>
<li><a href="<?php echo $this->url(array('module' => 'byzantinecoins'),NULL, true);?>" title="Read an introduction on Byzantine coins">Introduction </a></li>
<li><a href="<?php echo $this->url(array('module' => 'byzantinecoins','controller' =>'rulers'),NULL, true);?>" title="Learn more about the issuers of the Byzantine period">Issuing rulers</a></li>
<li><a href="<?php echo $this->url(array('module' => 'byzantinecoins','controller'  => 'mints'),NULL,true);?>" title="Issuing mints of the Byzantine period">Issuing mints</a></li>
<li><a href="<?php echo $this->url(array('module' => 'byzantinecoins', 'controller' =>  'denominations'),NULL,true);?>" title="Denominations of the Byzantine period">Denominations</a></li>
<li><a href="<?php echo $this->url(array('module' => 'database','controller' => 'search','action' => 'byzantinenumsimatics'),NULL,true);?>" title="Search for coins of the Byzantine period">Search</a></li>
</ul>
</li>
<li><a href="#">Other numismatic periods</a>
<ul>
<li><a href="<?php echo $this->url(array('module'=>'ironagecoins'),NULL, true);?>" title="Learn about Iron age coins">Iron age coins</a></li>
<li><a href="<?php echo $this->url(array('module'=>'romancoins'),NULL, true);?>" title="Learn about Roman coins">Roman coins</a></li>
<li><a href="<?php echo $this->url(array('module'=>'greekromancoins'),NULL, true);?>" title="Learn about Greek and Roman coins">Greek &amp; Roman coins</a></li>
<li><a href="<?php echo $this->url(array('module'=>'byzantinecoins'),NULL, true);?>" title="Learn about Byzantine coins">Byzantine coins</a></li>
<li><a href="<?php echo $this->url(array('module'=>'earlymedievalcoins'),NULL, true);?>" title="Learn about Early Medieval coins">Early Medieval coins</a></li>
<li><a href="<?php echo $this->url(array('module'=>'medievalcoins'),NULL, true);?>" title="Learn about Medieval coins">Medieval coins</a></li>
<li><a href="<?php echo $this->url(array('module'=>'postmedievalcoins'),NULL, true);?>" title="Learn about Post Medieval coins">Post Medieval  coins</a></li>
</ul>
</li>
</ul>

<div id="enhanced">
<h4>Data enhanced by:</h4>

<img src="/images/logos/calais.png" alt="The Open Calais logo" width="52" height="68"/><img src="/images/logos/geoplanet.png" alt="Yahoo geoplanet logo" height="68" width="70"/>
<img src="<?php echo $this->baseUrl();?>/images/logos/dbpedia.png" alt="Dbpedia's logo" height="43" width="70" />
</div>