<ul  id="menu1" class="menu collapsible">
<li><a href="<?php echo $this->url(array('module'=>'contacts','controller' => 'staff'),null,true);?>" title="Find contact details for our staff">Contact list</a></li>
<li><a href="<?php echo $this->url(array('module' => 'contacts','controller'=>'staff','action'=>'map'),null,true);?>" title="View our office locations">Contact map</a></li>
<li><a href="<?php echo $this->url(array('module' => 'contacts','controller' => 'alumni'),null,true);?>" title="View Scheme alumni statistics">Scheme Alumni</a></li>
<li><a href="<?php echo $this->url(array('module'=>'contacts','controller'=>'coroners'),null,true);?>" title="View coroners' details">Coroners' details</a></li>
<li><a href="<?php echo $this->url(array('module'=>'contacts','controller'=>'coroners','action' => 'map'),null,true);?>" title="View coroners' locations on map">Coroners mapped</a></li>
</ul>
