<ul id="menu1" class="menu collapsible expandfirst">
<?php $module = Zend_Controller_Front::getInstance()->getRequest()->getModuleName(); ?>

<li><a href="#">Greek and Roman Provincial coins</a>
<ul>
<li><a href="<?php echo $this->url(array('module'=> $module),NULL, true);?>" title="An introduction to Greek and Roman coins">Introduction </a></li>
<li><a href="<?php echo $this->url(array('module'=> $module,'controller'=> 'rulers'),NULL, true);?>" title="Issuing rulers of the Greek and Roman provincial period">Issuing rulers</a></li>
<li><a href="<?php echo $this->url(array('module'=> $module,'controller' => 'mints'),NULL,true);?>" title="Issuing mints of the Greek and Roman Provincial period">Issuing mints</a></li>
<li><a href="<?php echo $this->url(array('module'=> $module,'controller' =>'denominations'),NULL,true);?>" title="Denominations of the Greek and Roman provincial period">Denominations</a></li>
</li>
<li><a href="<?php echo $this->url(array('module'=> 'database','controller' =>'search','action' => 'greekroman'),NULL,true);?>" title="Search for the Greek and Roman provincial period">Search</a></li>
</ul>
<li><a href="#">Other numismatic periods</a>
<ul>
<li><a href="<?php echo $this->url(array('module'=>'ironagecoins'),NULL, true);?>" title="Learn about Iron age coins">Iron age coins</a></li>
<li><a href="<?php echo $this->url(array('module'=>'romancoins'),NULL, true);?>" title="Learn about Roman coins">Roman coins</a></li>
<li><a href="<?php echo $this->url(array('module'=>'greekromancoins'),NULL, true);?>" title="Learn about Greek and Roman coins">Greek &amp; Roman coins</a></li>
<li><a href="<?php echo $this->url(array('module'=>'byzantinecoins'),NULL, true);?>" title="Learn about Byzantine coins">Byzantine coins</a></li>
<li><a href="<?php echo $this->url(array('module'=>'earlymedievalcoins'),NULL, true);?>" title="Learn about Early Medieval coins">Early Medieval coins</a></li>
<li><a href="<?php echo $this->url(array('module'=>'medievalcoins'),NULL, true);?>" title="Learn about Medieval coins">Medieval coins</a></li>
<li><a href="<?php echo $this->url(array('module'=>'postmedievalcoins'),NULL, true);?>" title="Learn about Post Medieval coins">Post Medieval  coins</a></li>

</ul>
</li>

</ul>
<div id="enhanced">
<h4>Data enhanced by:</h4>

<img src="/images/logos/calais.png" alt="The Open Calais logo" width="52" height="68"/><img src="/images/logos/geoplanet.png" alt="Yahoo geoplanet logo" height="68" width="70"/>
<img src="<?php echo $this->baseUrl();?>/images/logos/dbpedia.png" alt="Dbpedia's logo" height="43" width="70" />
</div>