<ul id="menu1" class="menu collapsible">
<li><a href="<?php echo $this->url(array('module' => 'info'),'default',true);?>" title="Information about our site">About the site</a></li>
<li><a href="<?php echo $this->url(array('module' => 'info','controller' => 'content','action' => 'page','slug' => 'accessibility'),'i',true);?>" title="Information about our site\'s accessibility">Accessibility</a></li>
<li><a href="<?php echo $this->url(array('module' => 'info','controller' => 'content','action' => 'page','slug' => 'termsandconditions'),'i',true);?>" title="Read about our terms and conditions - nothing onerous">Terms of Use</a></li>
<li><a href="<?php echo $this->url(array('module' => 'info','controller' => 'content','action' => 'page','slug' => 'privacy'),'i',true);?>" title="Read about our privacy policy">Privacy & Cookies</a></li>
<li><a href="<?php echo $this->url(array('module' => 'info','controller' => 'content','action'=> 'page','slug' => 'foi'),'i',true);?>" title="Freedom of information requests and how to submit one">Freedom of Information</a></li>
<li><a href="<?php echo $this->url(array('module' => 'info','controller' => 'content','action' => 'page','slug' => 'rss'),'i',true);?>" title="Read about available RSS and Atom feeds">RSS feeds</a></li>
<li><a href="<?php echo $this->url(array('module' => 'database','controller' => 'oai','action' => 'index'),'default',true);?>" title="Read about our OAI server access">OAI access</a></li>
</ul>
