<ul id="menu1" class="menu collapsible expandfirst">
<li><a href="#">Iron age coins</a>
<ul>
<?php $module = Zend_Controller_Front::getInstance()->getRequest()->getModuleName(); ?>
<li><a href="<?php echo $this->url(array('module' => $module),null,true);?>" title="An intro to Iron Age coins">Introduction</a></li>
<li><a href="<?php echo $this->url(array('module' => $module, 'controller'=> 'rulers'),null,true);?>" title="Learn about issuing Iron Age issuers">Issuing rulers</a></li>
<li><a href="<?php echo $this->url(array('module' => $module, 'controller'=>'denominations'),null,true);?>" title="Learn about Iron Age denominations">Denominations</a></li>
<li><a href="<?php echo $this->url(array('module' => $module, 'controller'=> 'regions'),null,true);?>" title="Learn about the geography of the Iron Age">Geographic regions</a></li>
<li><a href="<?php echo $this->url(array('module' => $module, 'controller'=> 'tribes'),null,true);?>" title="Learn about Iron Age tribal connections">Tribes</a></li>
<li><a href="<?php echo $this->url(array('module' => $module, 'controller' => 'mints'),null,true);?>" title="Learn about Iron Age issuing mints">Issuing mints</a></li>
<li><a href="<?php echo $this->url(array('module' => $module, 'controller' => 'vanarsdelltypes'),null,true);?>" title="Learn about Van Arsdell types">Van Arsdell types</a></li>
<li><a href="<?php echo $this->url(array('module' => $module, 'controller' => 'macktypes'),null,true);?>" title="Learn about Mack types">Mack types</a></li>
<li><a href="<?php echo $this->url(array('module' => $module, 'controller' => 'allentypes'),null,true);?>" title="Learn about Allan types">Allen types</a></li>
<li><a href="<?php echo $this->url(array('module' => 'database', 'controller' => 'search','action' => 'ironagenumismatics'),null,true);?>" title="Search for Iron Age coins">Search</a></li>
</ul>
<li><a href="#">Other numismatic periods</a>
<ul>
<li><a href="<?php echo $this->url(array('controller'=>'byzantinecoins'),NULL, true);?>" title="Learn about Byzantine coins">Byzantine coins</a></li>
<li><a href="<?php echo $this->url(array('controller'=>'romancoins'),NULL, true);?>" title="Learn about Roman coins">Roman coins</a></li>
<li><a href="<?php echo $this->url(array('controller'=>'earlymedievalcoins'),NULL, true);?>" title="Learn about Early Medieval coins">Early Medieval coins</a></li>
<li><a href="<?php echo $this->url(array('controller'=>'greekromancoins'),NULL, true);?>" title="Learn about Greek and Roman provincial coins">Greek &amp; Roman coins</a></li>
<li><a href="<?php echo $this->url(array('controller'=>'medievalcoins'),NULL, true);?>" title="Learn about Medieval coins">Medieval coins</a></li>
<li><a href="<?php echo $this->url(array('controller'=>'postmedievalcoins'),NULL, true);?>" title="Learn about Post Medieval coins">Post Medieval  coins</a></li>
</ul>
</li>
</ul>

<div id="enhanced">
<h4>Data enhanced by:</h4>

<img src="/images/logos/calais.png" alt="The Open Calais logo" width="52" height="68"/><img src="/images/logos/geoplanet.png" alt="Yahoo geoplanet logo" height="68" width="70"/>
<img src="<?php echo $this->baseUrl();?>/images/logos/dbpedia.png" alt="Dbpedia's logo" height="43" width="70" />
</div>