<div id="paging">
<?php if ($this->pageCount): ?> 
<p><?php echo $this->firstItemNumber; ?> - <?php echo $this->lastItemNumber; ?> of <?php echo number_format($this->totalItemCount,0);?> records.</p>
<?php $this->headTitle(' Page: ' . $this->current);?>
<ul id="pagination">
<li><?php if(isset($this->previous)): ?>
<a href="<?php echo $this->url(array('page' => $this->first)); ?>">First page</a>
<a href="<?php echo $this->url(array('page' => $this->previous)); ?>">&laquo; Previous</a>
<?php else: ?>
<span class="previous-off">&laquo; Previous</span>
<?php endif; ?>
</li>
<?php foreach ($this->pagesInRange as $page): ?>
<li> 
<?php if ($page != $this->current): ?>
<a href="<?php echo $this->url(array('page' => $page)); ?>" ><?php echo $page; ?></a>
</li>  
<?php else: ?>
<a href="#" class="active"><?php echo $page; ?></a>
</li>  
<?php endif; ?>
<?php endforeach; ?>
<li class="next">
<?php if (isset($this->next)): ?> 
<a href="<?= $this->url(array('page' => $this->next)); ?>">Next &raquo;</a>
<?php else: ?> 
<span class="next-off">Next &raquo;</span>
<?php endif; ?>
<?php if (isset($this->next)): ?>
<a href="<?php echo $this->url(array('page' => $this->last)); ?>">Last page</a>
<?php else: ?>
<span class="disabled">Last</span>
<?php endif; ?>
</li>
</ul> 
<?php endif; ?>
</div>