<div id="paging"><p><?php if ($this->pageCount): ?> 

<?= $this->firstItemNumber; ?> - <?= $this->lastItemNumber; ?> 
of <?= $this->totalItemCount; ?> records.</p>
<?php $this->title .= ' page' . $this->firstItemNumber . ' - ' . $this->lastItemNumber;?>

<?php
$queryString = ($_SERVER['QUERY_STRING'] != '') ? '?' . $_SERVER['QUERY_STRING'] : '';
?> 

<ul id="pagination">
<!-- Previous page link --> 
<li><?php if (isset($this->previous)): ?> <a href="<?php echo $this->url(array('page' => $this->first)); ?>">
    First page 
  </a> <a href="<?= $this->url(array('page' => $this->previous)); ?>">&laquo; Previous</a> <?php else: ?><span class="previous-off">< Previous</span><?php endif; ?></li>

<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?><li> 
  <?php if ($page != $this->current): ?><a href="<?= $this->url(array('page' => $page)). $queryString;  ?>" ><?= $page; ?></a></li>  
  <?php else: ?>
<a href="#" class="active"><?= $page; ?></a>
  <?php endif; ?></li>
<?php endforeach; ?>
<li class="next">
<!-- Next page link --> 
<?php if (isset($this->next)): ?> 
  <a href="<?= $this->url(array('page' => $this->next)). $queryString;  ?>">Next ></a>
<?php else: ?> 
  <span class="next-off">Next &raquo;</span>
<?php endif; ?> 
<?php if (isset($this->next)): ?>
  <a href="<?php echo $this->url(array('page' => $this->last)); ?>">
    Last page
  </a>
<?php else: ?>
  <span class="disabled">Last</span>
<?php endif; ?>
</li>
</ul> 
<?php endif; ?>
<p>&nbsp;</p>
</div>