<ul id="menu1" class="menu collapsible">
<li><a href="<?php echo $this->url(array('module' => 'research','controller' => 'index'),'default',true);?>" title="Research section home">Research</a></li>
<li><a href="<?php echo $this->url(array('module' => 'research','controller' => 'projects'),'default',true);?>" title="View our research register">Research projects</a></li>
<li><a href="<?php echo $this->url(array('module' => 'research','controller' => 'projects','action' => 'suggested'),'default',true);?>" title="Some topics we believe need investigating">Suggested research projects</a></li>
<li><a href="<?php echo $this->url(array('module' => 'research','controller' => 'datatransfer'),'default',true);?>" title="Data transfer to third parties">Data transfer</a></li>
<li><a href="<?php echo $this->url(array('module' => 'research','controller' => 'datatransfer','action' => 'hers'),'default',true);?>" title="Which HERS have signed our agreement"><?php echo $this->acronyms('HER');?> signup</a></li>
</ul>
