<div id="tagfind">
<?php 


//$this->tagform->findID->setValue($this->finds['0']['secuid']);


//echo $this->tagform;

?>
<div id="tags">

<?php 

	$auth = Zend_Auth::getInstance();
	if($auth->hasIdentity())
	{
	$user = $auth->getIdentity();
	$id = $user->id;
	}
	else 
	{
	$id = '3';
	}
	$description = ' ';
	if($this->findspots != NULL) {
	if(!isset($this->findspots['0']['knownas'])){
	$description .= $this->findspots['0']['parish'];
	}
	$description .= ', County: ';
	$description .= $this->findspots['0']['county'];
	$description .= ' , District: ';
	$description .= $this->findspots['0']['district'];
	$description .= ' , Region: ';
	$description .= $this->findspots['0']['region'];
	}
	$description .= ' ,Country:  ';
	$description .= 'United Kingdom ';
	$description .= strip_tags($this->finds['0']['description']);
	$description .= ' ';
	$description .= strip_tags($this->finds['0']['notes']);
	$description .= ' ';
	$description .= $this->finds['0']['broadperiod'];
	
	if($this->coins != NULL) {
	
	foreach($this->coins['0'] as $c => $value) {
	$description .= $value . ' ';
	}
	}

	$recordID = $this->finds['0']['id'];
	//Zend_Debug::dump($description);
// $this->opencalais($recordID,$id,$description);
 $this->placemaker($recordID,$id,$description);

?>
</div>
</div>

