<?php
$allowed = array('flos','fa','admin');
$auth = Zend_Auth::getInstance();
if($auth->hasIdentity())
{
$user = $auth->getIdentity();
{

$controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();

?>

<ul id="menu1" class="menu collapsible">
<li><a href="<?php echo $this->url(array('module' => 'users','controller' => 'named'),null,true);?>" title="View all our registered users">View all users</a></li>
<li><a href="<?php echo $this->url(array('module' => 'users','controller' => 'audit','action' => 'logins'),null,true);?>" title="When have I logged in and where from">Login history</a></li>
<?php
if(in_array($user->role,$allowed)) {
?>
<li><a href="<?php echo $this->url(array('module' => 'users','controller' => 'news'),null,true);?>" title="Change and update news stories you entered">Administer news</a></li>
<li><a href="<?php echo $this->url(array('module' => 'users','controller' => 'events'),null,true);?>" title="Change and update events you entered">Administer events</a></li>
<?php
}
?>
<li><a href="<?php echo $this->url(array('module' => 'users','controller'=>'records'),null,true);?>" title="View finds recorded for me by the Scheme">My finds recorded by FLOs</a></li>

<li><a href="<?php echo $this->url(array('module' => 'database','controller'=>'myscheme','action'=>'myfinds'),null,true);?>" title="View finds I have recorded">Finds I recorded</a></li>
<li><a href="<?php echo $this->url(array('module' => 'database','controller'=>'myscheme','action'=>'myinstitution'),null,true);?>" title="View finds my institution has recorded">My institution's finds</a></li>
<li <?php if($controller == 'search') { echo 'class="expandfirst"';}?>><a href="#" title="Expand search">Search</a>
<ul>
<li><a href="<?php echo $this->url(array('module' => 'users','controller' => 'search'),null,true);?>" title="Facts about your searches">My search</a></li>
<li><a href="<?php echo $this->url(array('module' => 'users','controller' => 'search','action' => 'history'),null,true);?>" title="View your search history">History</a></li>
<li><a href="<?php echo $this->url(array('module' => 'users','controller' => 'search','action' => 'saved'),null,true);?>" title="View all your saved searches">Saved searches</a></li>
</ul>
</li>
<li><a href="<?php echo $this->url(array('module' => 'database','controller' => 'myscheme','action' => 'myimages'),null,true);?>" title="View all images I have added">My images</a></li>
<li><a href="<?php echo $this->url(array('module' => 'users','controller' => 'social',),null,true);?>" title="Administer my social sites available to other users">My social web</a></li>
<li><a href="<?php echo $this->url(array('module' => 'users','controller' => 'interests'),null,true);?>" title="Update my interests">My interests</a></li>
<li><a href="<?php echo $this->url(array('module' => 'users','controller' => 'education'),null,true);?>" title="Update my interests">My educational background</a></li>
<li <?php if($controller == 'comments') { echo 'class="expandfirst"';}?>><a href="#" title="Expand comments section">Comments</a>
<ul>
<li><a href="<?php echo $this->url(array('module' => 'users','controller' => 'comments','action' => 'imade'),null,true);?>" title="View my comments">My comments</a></li>
<li><a href="<?php echo $this->url(array('module' => 'users','controller' => 'comments','action' => 'onmine'),null,true);?>" title="View all comments on my records">Comments on my records</a></li>
</ul>
</li>
</ul>
<?php

}
}
?>

