<p>Dear <?php $this->escape($this->comment_author);?></p>
<p>Your comment has now been published at 
<a href="" title="View your comment"><?php echo Zend_Registry::get('siteurl');?>
    /database/artefacts/record/id/<?php
echo $this->comment_findID;?>"><?php echo $this->old_findID;?></a>.</p>
<p>For your own reference, this is what you submitted:</p>

<?php echo $this->purify($this->comment);?>

<p>Many thanks for taking the time to comment!</p>
<p>Yours sincerely,</p>
<p>The staff of the Portable Antiquities Scheme.</p>
