<?php $this->mail->setSubject('New password request for the PAS website');?>
<p>Dear <?php echo $this->escape($this->splitName($this->fullname));?>,</p>

<p>Thank you for requesting a new password. This is below:</p>

<p><?php echo $this->password;?></p>

<p>If you still have problems accessing your account, please do contact us.</p>

<p>Yours,</p>

<p>The Portable Antiquities Scheme</p>