<entry>
		<title><?php echo $this->xmlconvert($this->old_findID); ?></title>
		<link href="<?php echo 'http://'.$_SERVER['SERVER_NAME'].$this->url(array('module' => 'database','controller' => 'artefacts',
	'action' => 'record', 'id' => $this->id),NULL,true); ?>" />
		<id><?php echo 'http://'.$_SERVER['SERVER_NAME'].$this->url(array('module' => 'database','controller' => 'artefacts',
	'action' => 'record', 'id' => $this->id),NULL,true); ?>#When:<?php echo date(DATE_W3C,strtotime( $this->created));?></id>
		<updated><?php echo date(DATE_ATOM,strtotime( $this->created));?></updated>
		<summary><?php echo $this->ellipsisstring($this->xmlconvert($this->description),300); ?></summary>
	</entry>
