<item>
<title><?php echo $this->xmlconvert($this->old_findID); ?></title>
<link><?php echo 'http://'.$_SERVER['SERVER_NAME'].$this->url(array('module' => 'database','controller' => 'artefacts',
	'action' => 'record', 'id' => $this->id),NULL,true); ?></link>
<guid><?php echo 'http://'.$_SERVER['SERVER_NAME'].$this->url(array('module' => 'database','controller' => 'artefacts',
	'action' => 'record', 'id' => $this->id),NULL,true); ?>#When:<?php echo date(DATE_W3C,strtotime( $this->created));?></guid>
<description><?php echo $this->xmlconvert($this->description); ?></description>
<dc:subject><?php echo $this->xmlconvert('archaeology'); ?></dc:subject>
<dc:date><?php echo date(DATE_W3C,strtotime( $this->created));?></dc:date>
</item>

