<?php
$this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/jquery.lightbox.js',$type='text/javascript');
?>
<?php $this->jQuery()->javascriptCaptureStart(); ?>
jQuery(document).ready(function($) {
 $('a[rel*=lightbox]').lightBox() 
    }
);
<?php $this->jQuery()->javascriptCaptureEnd(); ?>
<?php $this->MetaBase('A list of all recently released news stories from the Scheme and external sources. This is compiled infrequently.','news','portable antiquities,news,stories,central unit,website','dc.keywords');
?>
<h2>News from the Scheme</h2>
<?php if (count($this->news)): ?>
<?php echo $this->partialLoop('partials/news/newsTable.phtml',$this->news);?>
<?php else:?>
<p>There are no news articles availble at the moment.</p>
<?php endif; ?>
<?= $this->paginationControl($this->news, 'Sliding', 'structure/pagination.phtml'); ?>
