<h2>Hoard name: <?php echo $this->escape($this->term);?></h2>
<?php
$string = '<p><a href="'.$this->url(array('module' => 'database','controller'=>'hoards','action'=>'edit','id'=>$this->id),null,true).'" title="Edit this hoard's details">Edit</a>
<a href="'.$this->url(array('controller'=>'database','action'=>'delete', 'id'=>$this->id),null,true).'" title="Delete this hoard's details">Delete</a></p>';
echo $this->allowedtest($string);?>
<p>Broadperiod attributed: <?php echo $this->t;?></p>
<?php echo $this->termdesc;?>

<p>View <a href="<?php echo $this->url(array('module' => 'database','controller' => 'search','action' => 'results','hoard' => '1','hID' => $this->id),null,true);?>" title="Search database for all records for <?php echo $this->escape($this->term);?>">all records</a> on our database attributed to this hoard.</p>
