<?php $this->headTitle('All messages submitted to the Scheme');?>
<h2>All messages submitted</h2>
<?php if(count($this->messages)):?>
<table class="stripeMe" cellspacing="0">
<thead>
	<tr>
	<th scope="col" id="author" class="manage-column column-author">Author</th>
	<th scope="col" id="comment" class="manage-column column-comment">Comment</th>
	<th scope="col" id="response" class="manage-column column-response">Status</th>
	<th scope="col">Actions</th>
	</tr>

</thead>


<tbody id="the-comment-list" class="list:comment">

<?php echo $this->partialLoop('partials/admin/messages.phtml', $this->messages) ?>

</tbody>

</table>
<?php else:?>
<p>No messages are listed or available to you</p>
<?php endif;?>
<?echo $this->paginationControl($this->messages, 'Sliding', 'structure/pagination.phtml'); ?>