<?php echo "\n";?>Coin data (numismatics)<?php echo "\n";?>
<?php if($this->d != NULL) :?>
Denomination: <?php echo $this->escape($this->d);?><?php echo "\n";?><?php endif;?>
<?php if($this->ruler_id != NULL) :?>
Ruler/issuer: <?php echo $this->escape($this->ruler1);?><?php echo "\n";?>
<?php endif;?>
<?php if($this->ruler2 != NULL) :?>
Secondary ruler/issuer: <?php echo $this->escape($this->ruler2);?><?php echo "\n";?>
<?php endif;?>
<?php if($this->tribe != NULL) :?>
Tribe: <?php echo $this->escape($this->tribe);?><?php echo "\n";?>
<?php endif;?>
<?php if($this->a != NULL):?>
Geographic provenance: <?php echo $this->escape($this->a);?><?php echo "\n";?>
<?php endif;?>
<?php if($this->allen_type != NULL):?>
Allen Type: <?php echo $this->escape($this->allen_type);?><?php echo "\n";?>
<?php endif;?>
<?php if($this->mack != NULL):?> Mack Type: <?php echo $this->escape($this->mack);?><?php echo "\n";?>
<?php endif;?>
<?php if($this->va_type != NULL):?>
Van Arsdell Type: <?php echo $this->escape($this->va_type);?><?php echo "\n";?>
<?php endif;?>
<?php if($this->mint_name != NULL) :?>
Mint or issue place: <?php echo $this->escape($this->mint_name);?><?php echo "\n";?>
<?php endif;?>
<?php if($this->obverse_description != NULL) : ?>
Obverse description: <?php echo $this->obverse_description;?><?php echo "\n";?>
<?php endif;?>
<?php if($this->obverse_inscription != NULL) :?>
Obverse inscription: <?php echo $this->obverse_inscription;?><?php echo "\n";?>
<?php endif;?>
<?php if($this->reverse_description != NULL) :?>
Reverse description: <?php echo $this->reverse_description;?><?php echo "\n";?>
<?php endif;?>
<?php if($this->reverse_inscription != NULL) :?>
Reverse inscription: <?php echo $this->reverse_inscription;?><?php echo "\n";?>
<?php endif;?>
<?php if($this->die_axis_name != NULL) : ?>
Die axis measurement: <?php echo $this->escape($this->die_axis_name);?><?php echo "\n";?>
<?php endif;?>
<?php if($this->wear != NULL) : ?>
Degree of wear: <?php echo $this->escape($this->wear);?><?php echo "\n";?>
<?php endif;?>
<?php echo "\n";?>