<?php echo "\n";?>
Coin data (numismatics)
<?php echo "\n";?>
<?php if(!is_null($this->d)) :?>
Denomination: <?php echo $this->escape($this->d);?>
<?php echo "\n";?>
<?php endif; ?>
<?php if(!is_null($this->ruler_id)) :?>
Ruler/issuer: <?php echo $this->escape($this->ruler1);?>
<?php echo "\n";?>
<?php endif;?>
<?php if(!is_null($this->mint_name)):?>
Mint or issue place: <?php echo $this->escape($this->mint_name);?>
<?php echo "\n";?>
<?php endif;?>
<?php if(!is_null($this->category)):?>
Category: <?php echo $this->escape($this->category);?>
<?php echo "\n";?>
<?php endif;?>
<?php if(!is_null($this->type)):?>
Type: <?php echo $this->escape($this->type);?>
<?php echo "\n";?>
<?php endif;?>
<?php if(!is_null($this->obverse_description)):?>
Obverse description: <?php echo ucfirst($this->escape($this->obverse_description));?>
<?php echo "\n";?>
<?php endif;?>
<?php if(!is_null($this->obverse_inscription)):?>
Obverse inscription: <?php echo ucfirst($this->obverse_inscription);?>
<?php echo "\n";?>
<?php endif;?>
<?php if(!is_null($this->reverse_description)):?>
Reverse description: <?php echo ucfirst($this->reverse_description);?>
<?php echo "\n";?>
<?php endif;?>
<?php if(!is_null($this->reverse_inscription)):?>
Reverse inscription: <?php echo ucfirst($this->reverse_inscription);?>
<?php echo "\n";?>
<?php endif;?>
<?php if(!is_null($this->die_axis_name)):?>
Die axis measurement: <?php echo $this->escape($this->die_axis_name);?>
<?php echo "\n";?>
<?php endif;?>
<?php if(!is_null($this->wear)):?>
Degree of wear: <?php echo $this->escape($this->wear);?>
<?php echo "\n";?>
<?php endif;?>
<?php echo "\n";?>