<?php echo "\n";?>Coin data (numismatics)<?php echo "\n";?>
<?php if(!is_null($this->d)) : ?>
Denomination: <?php echo $this->escape($this->d);?><?php echo "\n";?>
<?php endif;?>
<?php if(!is_null($this->ruler1)) : ?>
Ruler/issuer: <?php echo $this->escape($this->ruler1);?><?php echo "\n";?>
<?php endif;?>
<?php if(!is_null($this->period_name)) : ?>
Reece period: <?php echo $this->escape($this->period_name);?><?php echo "\n";?>
<?php endif;?>
<?php if(!is_null($this->mint_name)) : ?>
Mint or issue place: <?php echo $this->escape($this->mint_name);?><?php echo "\n";?>
<?php endif;?>
<?php if(!is_null($this->obverse_description)) : ?>
Obverse description: <?php echo $this->obverse_description;?><?php echo "\n";?>
<?php endif;?>
<?php if(!is_null($this->obverse_inscription)) : ?>
Obverse inscription: <?php echo $this->obverse_inscription;?><?php echo "\n";?>
<?php endif;?>
<?php if(!is_null($this->reverse_description)) : ?>
Reverse description: <?php echo $this->reverse_description;?><?php echo "\n";?>
<?php endif;?>
<?php if(!is_null($this->reverse_inscription)) : ?>
Reverse inscription: <?php echo $this->reverse_inscription;?><?php echo "\n";?>
<?php endif;?>
<?php if(!is_null($this->die_axis_name)) : ?>
Die axis measurement: <?php echo $this->escape($this->die_axis_name);?><?php echo "\n";?>
<?php endif;?>
<?php if(!is_null($this->wear)) : ?>
Degree of wear: <?php echo $this->escape($this->wear);?><?php echo "\n";?>
<?php endif;?>
<?php if(!is_null($this->name)) : ?>
Republican moneyer: <?php echo $this->escape($this->name);?><?php echo "\n";?>
<?php endif;?>
<?php if(!is_null($this->revtypeID)) : ?>
Fourth Century reverse type: <?php echo $this->escape($this->revname);?><?php echo "\n";?>
<?php endif;?>
<?php echo "\n";?>