<?php echo "\n";?>
Spatial data 
<?php echo "\n";?>
<?php if(!is_null($this->region)) :?>
Region: <?php echo $this->escape(ucwords(strtolower($this->region)));?>
<?php echo "\n";?>
<?php endif;?>
<?php if(!is_null($this->county)) :?>
County: <?php echo $this->escape(ucwords(strtolower($this->county)));?>
<?php echo "\n";?>
<?php endif;?>
<?php if(!is_null($this->district)) :?>
District: <?php echo $this->escape(ucwords(strtolower($this->district)));?>
<?php echo "\n";?>
<?php endif;?>

<?php if(!is_null($this->parish) && (empty($this->knownas))):?>
Parish: <?php echo  ucwords(strtolower($this->parish));?>
<?php echo "\n";?>
<?php if(!is_null($this->knownas)) :?>
To be known as: <?php echo $this->escape($this->knownas);?>
<?php echo "\n";?>
<?php endif;?>
<?php endif;?>
<?php if(!is_null($this->gridref) && (empty($this->knownas))) { ?>
<p>
Restricted 4 Figure grid reference: <?php echo $this->fourFigure;?>
<?php echo "\n";?>
Grid reference source: <?php echo $this->escape($this->source);?>
<?php echo "\n";?>
Grid reference accurate to a <?php echo $this->GetAccuracy($this->gridref);?>  metre square
<?php echo "\n";?>
</p>
<?php endif;?>
<?php if(!is_null($this->method)) :?>
Method of discovery: <?php echo $this->escape($this->method);?>
<?php echo "\n";?>
<?php endif;?>
<?php if(!is_null($this->disccircum)) :?>
Discovery circumstances:  <?php echo $this->escape($this->disccircum);?>
<?php echo "\n";?>
<?php endif;?>
<?php if(!is_null($this->curr_loc)) :?>
Current location: <?php echo $this->escape($this->curr_loc);?>
<?php echo "\n";?>
<?php endif;?>
<?php if(!is_null($this->landvalue)) :?>
General landuse: <?php echo $this->landvalue;?>
<?php echo "\n";?>
<?php endif;?>
<?php if(!is_null($this->landuse)) :?>
Specific landuse: <?php echo $this->escape($this->landuse);?>
<?php endif;?>
<?php echo "\n";?>