<?php     
$this->headTitle('All Van Arsdell types recorded on the database');?>
<h2>Van Arsdell types</h2>
<?php if($this->macks):?> 
<table summary="A list of all Van Arsdell types in use" class="stripeMe">
<caption>All Mack types</caption>
<thead>
<tr>
<th>Type name</th>
<th>Totals recorded</th>
</tr>
</thead>
<tbody>
<?php echo $this->partialLoop('partials/numismatics/va.phtml',$this->macks);?>
</tbody>
</table>
<?php $this->paginationControl($this->macks, 'Sliding', 'structure/pagination.phtml'); ?>

<?php else:?>
<p>No Allen types available</p>
<?php endif;?>