<li>
<a href="<?php echo $this->baseUrl().'/database/record/id/'.$this->escape($this->n);?>"><?php echo $this->old_findID;?></a> : a  <?php echo $this->broadperiod;?> <?php echo strtolower($this->objecttype);?> <?php echo ucfirst(strtolower($this->county));?><br>
<?php echo $this->ellipsisstring($this->description,300);?><?php if($this->i != NULL): ?>
<img src="http://www.findsdatabase.org.uk/view/thumbnails/pas/<?php echo $this->i;?>.jpg" title="" style="padding:10px;border:3px solid #8B0000;"/>
<?php endif;?>

</li>
