<?php echo $this->partialLoop('partials/numismatics/romanDenom.phtml', $this->denoms) ;?>
<?php if(count($this->emps)):?>
<h3>Issued by</h3>
<ul id="related">
<?php echo $this->partialLoop('partials/numismatics/empDenom.phtml', $this->emps);?>
</ul>
<?php endif;?>
<?php if($this->images):?>
<h3>Latest examples recorded</h3>
<div id="latest">
<?php echo $this->partialLoop('partials/database/imagesPaged.phtml',$this->images);?>
</div>
<?php endif;?>