<?php echo $this->partialLoop('partials/numismatics/romanDenom.phtml', $this->denoms) ;?>
<?php if(count($this->emps)):?>
<h3>Issued by</h3>
<ul id="related">
<?php echo $this->partialLoop('partials/numismatics/empDenom.phtml', $this->emps);?>
</ul>
<?php endif;?>
<?php echo $this->latestRecords('denomination:' . Zend_Controller_Front::getInstance()->getRequest()->getParam('id')); ?>

<?php 
$this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/jquery.lightbox.js',$type='text/javascript'); 
$this->jQuery()->javascriptCaptureStart(); ?>
jQuery(document).ready(function($) {
$('a[rel*=lightbox]').lightBox() 
});
<?php $this->jQuery()->javascriptCaptureEnd(); ?>