<rally>
	<url>http://www.finds.org.uk/database/rallies/rally/id/<?php echo $this->id;?></url>
	<name><?php echo $this->rally_name;?></name>
	<geo>
	<county><?php echo $this->county;?></county>
	<district><?php echo $this->district;?></district> 
	<parish><?php echo $this->parish;?></parish>
	<ngr><?php echo $this->gridref;?></ngr>
	<fourFigure><?php echo $this->fourFigure;?></fourFigure>
	<easting><?php echo $this->easting;?></easting>
	<northing><?php echo $this->northing;?></northing>
	<one25k><?php echo $this->map25k;?></one25k>
	<one10k><?php echo $this->map10k;?></one10k>
	<lat><?php echo $this->latitude;?></lat>
	<lon><?php echo $this->longitude;?></lon>
	</geo>
	<dates>
	<datefrom><?php echo $this->df;?></datefrom> 
	<dateto><?php echo $this->dt;?></dateto>
	</dates>
	<metadata>
	<created><?php echo $this->created;?></created>
	<createdby><?php echo $this->fullname;?></createdby>
	<updated><?php echo $this->updated;?></updated>
	<updatedby><?php echo $this->fn;?></updatedby>
	</metadata>
</rally>