<?php echo '<?xml version="1.0" encoding="utf-8"?>';?>

<?php echo $this->docType();?>

<html 
	
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:foaf="http://xmlns.com/foaf/0.1/"
	xmlns:dc="http://purl.org/dc/elements/1.1/" 
	xmlns:batlas="http://atlantides.org/batlas/"
	xmlns:gml="http://www.opengis.net/gml/"
	xmlns:nm="http://nomisma.org/id/"
	xmlns:ov="http://open.vocab.org/terms/"
	xmlns:owl="http://www.w3.org/2002/07/owl#"
	xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
	xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
	xmlns:skos="http://www.w3.org/2008/05/skos#"
	xmlns:pas="http://www.finds.org.uk/rdf/"
	xmlns:google="http://rdf.data-vocabulary.org/#"
	xmlns:con="http://www.w3.org/2000/10/swap/pim/contact#"
	xmlns:geo="http://www.w3.org/2003/01/geo/wgs84_pos#"
	xmlns:c="http://s.opencalais.com/1/pred/"
	xmlns:bibo="http://purl.org/ontology/bibo/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
	xmlns:units="http://qudt.org/"
	xmlns:og="http://ogp.me/ns#"
	xmlns:fb="http://www.facebook.com/2008/fbml"
	xml:lang="en"
>
<head>

<?echo $this->headTitle(); ?>

<?echo $this->headMeta(); ?>


<?echo $this->headLink(); ?>


<?echo $this->headScript(); ?> 

	
</head>
<body>
<div id="container">


<div id="header">

<?php echo $this->layout()->header ?>

<div id="nav">
<?php echo $this->layout()->navigation ?>
</div>		

</div>


<div id="sidebar">
<?php echo $this->layout()->userdata;?>
<?php echo $this->layout()->sidebar; ?>
<?php echo $this->layout()->workflow;?>
<?php 
//echo $this->layout()->research;
?>
<?php echo $this->layout()->tag;?>
</div> 
	   
<div id="content">
<?php echo $this->layout()->breadcrumb;	?>
<?php echo $this->layout()->messages;?>
<?php echo $this->acronyms($this->layout()->content); ?>
<?php echo $this->layout()->contexts; ?>

</div>

<div id="footer">
<?php echo $this->layout()->footer; ?>
</div>

</div>
<?echo $this->jQuery(); ?>

<?php echo $this->inlineScript(); ?> 

<?php echo $this->layout()->analytics; ?> 


</body>
</html>