<?php $this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/jquery.autocomplete.pack.js',$type='text/javascript'); ?>
<?php $this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/autocompleteinitPeople.js',$type='text/javascript'); ?>
<?php $this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/ui.datepicker.js',$type='text/javascript'); ?>
<?php $this->headLink()->appendStylesheet($this->baseUrl().'/css/autocomplete.css')
->appendStylesheet($this->baseUrl().'/css/ui.datepicker.css');?>


<?php $this->jQuery()->javascriptCaptureStart() ?>
$(document).ready(function() {
$("#startDate").datepicker({ maxDate: '+6y'});
$("#endDate").datepicker({ maxDate: '+6y' });
});


<?php $this->jQuery()->javascriptCaptureEnd() ?>

<h2>Add a research project</h2>
<?php echo $this->form;?>