<?php
$this->headTitle('All images on the database');
$this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/jquery.lightbox.js',$type='text/javascript'); 
?>
<?php $this->jQuery()->javascriptCaptureStart() ?>
jQuery(document).ready(function($) {
 $('a[rel*=lightbox]').lightBox() 
    })
$(function() {
<?php
$auth = Zend_Auth::getInstance();
if($auth->hasIdentity()){
$user = $auth->getIdentity();
{
if(in_array($user->role,array('flos','treasure','fa','admin'))) {
?>
	$('div.image-controls').css('visibility','hidden');
	$('div.thumbnail').each(function() {
		var controls = $(this).children('div.image-controls');
		$(this).hover(
			function() { $(controls).css('visibility','visible') },
			function() { $(controls).css('visibility','hidden') }
		);
	});	
<?php
}
}
}
?>
});
<?php $this->jQuery()->javascriptCaptureEnd() ?>
<?php 
$this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/jquery.autocomplete.pack.js',$type='text/javascript');
$this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/autocompleteinit.js',$type='text/javascript'); 
$this->headLink()->appendStylesheet($this->baseUrl().'/css/autocomplete.css')
?>


<h2>All images on the database</h2>
<div id="imagefilter">
<table><tr><?php echo $this->form;?></tr></table>
</div>
<?php if (count($this->results)): ?>
<div id="gallery">
<?php echo $this->partialLoop('partials/database/myimagesList.phtml',$this->results);?>
</div>
<div style="clear:both;">
<?php echo $this->paginationControl($this->paginator, 'Elastic', 'structure/pagination.phtml'); ?>
</div>
<?php else:?>
<p>You have added no images to our database.</p>
<?php endif; ?>
