<?php 
	
$this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/jquery.lightbox.js',
$type='text/javascript');

$this->jQuery()->javascriptCaptureStart() ?>
jQuery(document).ready(function($) {

 $('a[rel*=lightbox]').lightBox() 
    })
<?php $this->jQuery()->javascriptCaptureEnd() ?>
<?php $this->jQuery()->javascriptCaptureStart() ?>
 $(document).ready(function(){
 
if (GBrowserIsCompatible()) {
 	  var gmarkers = [];
      var htmls = [];
      var i = 0;
   	  var Icon = new GIcon();
      
      Icon.image = 'http://labs.google.com/ridefinder/images/mm_20_red.png';
      Icon.shadow = 'http://labs.google.com/ridefinder/images/mm_20_shadow.png';
      Icon.iconSize = new GSize( 12, 20 );
      Icon.shadowSize = new GSize( 22, 20 );
      Icon.iconAnchor = new GPoint( 6, 20 );
      Icon.infoWindowAnchor = new GPoint( 5, 1 );
      Icon.infoShadowAnchor = new GPoint( 5, 1 );
	  
	  var Yellow = new GIcon();
      Yellow.image = 'http://labs.google.com/ridefinder/images/mm_20_yellow.png';
      Yellow.shadow = 'http://labs.google.com/ridefinder/images/mm_20_shadow.png';
      Yellow.iconSize = new GSize( 12, 20 );
      Yellow.shadowSize = new GSize( 22, 20 );
      Yellow.iconAnchor = new GPoint( 6, 20 );
      Yellow.infoWindowAnchor = new GPoint( 5, 1 );
      Yellow.infoShadowAnchor = new GPoint( 5, 1 );
	  
	  
	  var Black = new GIcon();
      Black.image = 'http://labs.google.com/ridefinder/images/mm_20_black.png';
      Black.shadow = 'http://labs.google.com/ridefinder/images/mm_20_shadow.png';
      Black.iconSize = new GSize( 12, 20 );
      Black.shadowSize = new GSize( 22, 20 );
      Black.iconAnchor = new GPoint( 6, 20 );
      Black.infoWindowAnchor = new GPoint( 5, 1 );
      Black.infoShadowAnchor = new GPoint( 5, 1 );
	    
	  var Green = new GIcon();
      Green.image = 'http://labs.google.com/ridefinder/images/mm_20_green.png';
      Green.shadow = 'http://labs.google.com/ridefinder/images/mm_20_shadow.png';
      Green.iconSize = new GSize( 12, 20 );
      Green.shadowSize = new GSize( 22, 20 );
      Green.iconAnchor = new GPoint( 6, 20 );
      Green.infoWindowAnchor = new GPoint( 5, 1 );
      Green.infoShadowAnchor = new GPoint( 5, 1 );
	  
      var clusterIcon = new GIcon();
      clusterIcon.image = 'http://labs.google.com/ridefinder/images/mm_20_blue.png';
      clusterIcon.shadow = 'http://labs.google.com/ridefinder/images/mm_20_shadow.png';
      clusterIcon.iconSize = new GSize( 12, 20 );
      clusterIcon.shadowSize = new GSize( 22, 20 );
      clusterIcon.iconAnchor = new GPoint( 6, 20 );
      clusterIcon.infoWindowAnchor = new GPoint( 5, 1 );
      clusterIcon.infoShadowAnchor = new GPoint( 5, 1 );
   	
   	  var copyOSM = new GCopyrightCollection('<a href="http://www.openstreetmap.org/">OpenStreetMap</a>');
  	  copyOSM.addCopyright(new GCopyright(1,new GLatLngBounds(new GLatLng(-90, -180), new GLatLng(90, 180)),
    	0, ' '));
	
	  var osmLayer = new GTileLayer(copyOSM, 0, 18, {
    tileUrlTemplate: 'http://b.tile.cloudmade.com/BC9A493B41014CAABB98F0471D759707/998/256/{Z}/{X}/{Y}.png',
    isPng: true,
    opacity: 1.0
  });

	  
 	var osmMap = new GMapType(
    [osmLayer], // list of layers
    G_NORMAL_MAP.getProjection(), // borrow the Mercator projection from the standard map
    'OSM' // name should be short enough to fit in button
  );
   	  
   	  var map = new GMap2(document.getElementById("mapobjects"));
		
        map.addControl(new GSmallMapControl());
		map.addControl(new GMenuMapTypeControl());
		//map.addControl (new GHierarchicalMapTypeControl());
		map.addMapType(G_PHYSICAL_MAP);
		map.addMapType(osmMap);
		map.addMapType(G_SATELLITE_3D_MAP);
        map.setCenter(new GLatLng(52.6164, -1.0547), 6 , G_PHYSICAL_MAP);
		map.enableContinuousZoom();
		map.addControl(new GScaleControl());
    	map.disableScrollWheelZoom(); 
		map.enableRotation();	  
	  
	  <?php
		
		
$auth = Zend_Registry::get('auth');
$allowed = array('flos','research','hero','fa','admin','treasure');
if($auth->hasIdentity())
{
$user = $auth->getIdentity();
{
 if(!in_array($user->role,$allowed)) 
 {

		
	    
   echo "var mt = map.getMapTypes();for (var i=0; i<mt.length; i++) {
        mt[i].getMinimumResolution = function() {return 2;}
        mt[i].getMaximumResolution = function() {return 11;}
      }"; 
	  }
	  } 
	  
	  } else {
	   echo "var mt = map.getMapTypes();for (var i=0; i<mt.length; i++) {
        mt[i].getMinimumResolution = function() {return 2;}
        mt[i].getMaximumResolution = function() {return 11;}
      }"; 
	  }
	  ?>
	  var customIcons = [];
	  customIcons["review"] = Icon;
	  customIcons["quarantine"] = Black;
	  customIcons["published"] = Green;
	  customIcons["validation"] = Yellow;

      var clusterer = new Clusterer(map);
      clusterer.icon = clusterIcon;      
      clusterer.maxVisibleMarkers = 150;
      clusterer.gridSize = 18;
      clusterer.minMarkersPerClusterer = 2;
      clusterer.maxLinesPerInfoBox = 4;
	                  
      var request = GXmlHttp.create();
      request.open("GET", "<?php echo $this->baseUrl();?>/ajax/mapdata/ruler/<?php echo $this->emps['0']['pasID'];?>", true);
      request.onreadystatechange = function() {
        if (request.readyState == 4) {
          var xmlDoc = request.responseXML;
          var markers = xmlDoc.documentElement.getElementsByTagName("marker");
          for (var i = 0; i < markers.length; i++) {
          var lat = parseFloat(markers[i].getAttribute("lat"));
          var lng = parseFloat(markers[i].getAttribute("lng"));
          var point = new GLatLng(lat,lng);
          var html = markers[i].getAttribute("name");
          var label = markers[i].getAttribute("name");
		  var workflow = markers[i].getAttribute("workflow");
		 

          var marker = createMarker(point,label,html,Icon);
          clusterer.AddMarker(marker, label);
          }
         }
		 
		function createMarker(point,name,html,icon) {
        var marker = new GMarker(point, customIcons[workflow]);
		
		 GEvent.addListener(marker, "click", function(){ 
          marker.openInfoWindowHtml(html,{maxWidth:360,maxHeight:350});
  	  });
		
        
        gmarkers[i] = marker;
        htmls[i] = html;
        return marker;
      }
      }
      request.send(null);
 }
 
 
$('#tabs').tabs({ fx: { opacity: 'toggle' } }); 
$('#tabs').bind('tabsshow', function(event, ui) {
    if (ui.panel.id == "mapobjects") {
        map.checkResize();
    }	 

jQuery('a[href=#mapobjects]').bind('click',fixMap);

function fixMap(event) {
	  
	  
	  }
	
		
});

 });
<?php $this->jQuery()->javascriptCaptureEnd() ?>
<?php $this->jQuery()->addJavascriptFile('http://jquery-ui.googlecode.com/svn/tags/latest/ui/ui.tabs.js');
$this->inlineScript()->appendFile($this->baseUrl().'/js/maps/clusterer.js',$type='text/javascript');
?>


<?php echo $this->partialLoop('partials/numismatics/emperor.phtml',$this->emps);?>
<?php if($this->images):?>
<h3>Latest examples recorded</h3>
<div id="latest">
<?php echo $this->partialLoop('partials/database/imagesPaged.phtml',$this->images);?>
</div>
<?php endif;?>
<p></p>
<div id="tabs">
  <ul>
       
        <li><a href="#denominations"><span>Denominations issued</span></a></li>
		 <li><a href="#mints"><span>Issuing mints</span></a></li>
		<li><a href="#mapobjects"><span>Findspots</span></a></li>
		<?php if(!is_null($this->emps['0']['murdoch'])):?>
		<li><a href="#podcast"><span>Podcast</span></a></li>
		<?php endif;?>
    </ul>

<div id="denominations">
<h3>Denominations issued</h3>
<ul id="related">
<?php echo $this->partialLoop('partials/numismatics/denomruler.phtml',$this->denoms);?>

</ul>
</div>


<div id="mints">
<h3>Issuing mints</h3>
<ul id="related">
<?php echo $this->partialLoop('partials/numismatics/mints.phtml',$this->mints);?>
</ul>
</div>

<div id="mapobjects"></div>

<?php if(!is_null($this->emps['0']['murdoch'])):?>
<div id="podcast"><?php echo $this->emps['0']['murdoch'];?>
<p>This video has been embedded from <a href="http://adrianmurdoch.typepad.com/my_weblog/" title="Adrian's blog">Adrian Murdoch's</a> series of podcasts on the Emperors of Rome. 
Many thanks to him for allowing us to use these podcasts.</p></div>
<?php endif;?>

</div>