<?php 
$this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/jQueryLinkedSelect.js',$type='text/javascript'); 
$this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/coinslinkedselect.js',$type='text/javascript'); 
$this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/linkedinit.js',$type='text/javascript');
//$this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/jquery.autocomplete.pack.js',
//$type='text/javascript'); 
//$this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/autocompletecrime.js',
//$type='text/javascript'); 
$this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/ui.datepicker.js',
$type='text/javascript'); 
$this->headLink()->appendStylesheet($this->baseUrl().'/css/autocomplete.css')
				 ->appendStylesheet($this->baseUrl().'/css/ui.datepicker.css');
				 ?>
<h2>Add a new crime</h2>
<p><?php ucwords('Heritage crime intelligence report.');?></p>
<?php
echo $this->form;?>
<?php 
$this->jQuery()->javascriptCaptureStart();?>
$(document).ready(function(){
       $('form .info').hide();
$(':input').focus(function () { $(this).next().show("slow") });
$(':input').blur(function () { $(this).next().hide("slow") });
    
      
   
    });
	
<?php $this->jQuery()->javascriptCaptureEnd();?>
