<?php if ($this->crime) :?>
<h2>Delete a heritage crime</h2>
<p>Are you sure that you want to delete
'<?php echo $this->escape($this->crime->subject); ?>' 
</p>
<form action="<?php echo $this->url(array('module' => 'database','controller' => 'heritage','action'=>'delete'),null,true); ?>"
method="post">
<div>
<input type="hidden" name="id" value="<?php echo $this->crime->id; ?>" />
<input type="submit" name="del" value="Yes" />
<input type="submit" name="del" value="No" />
</div>
</form>
<?php else: ?>
<h2>There has been an error</h2>
<p>Cannot find the crime that you requested.</p>
<?php endif;?>