<?php 
$this->headTitle("Add a new decoration method");
$this->headScript()->prependFile($this->baseUrl().'/js/JQuery/jquery-1.2.3.min.js',$type='text/javascript'); ?>
<?php $this->headScript()->appendFile($this->baseUrl().'/js/JQuery/jquery.menu.js',$type='text/javascript'); ?>
<?php $this->headLink()->appendStylesheet($this->baseUrl().'/css/style.css')
->appendStylesheet($this->baseUrl().'/css/default.css');?>
<?php 
echo $this->form;
?>