<h2>Landuse types</h2>

<p><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'terminology','action' => 'addlanduse'),null,true);?>" title="Add a new landuse term">Add a new land use term</a></p>
<table class="stripeMe" summary="List of Landuses that the Scheme uses">
<thead>
<tr>
<th>Landuse term</th>
<th>Created</th>
<th>Created by</th>
<th>Updated</th>
<th>Updated by</th>
<th>Validity</th>
<th>Actions</th>
</tr>
</thead>
<tbody>
<?php echo $this->partialLoop('partials/admin/landuseListTable.phtml',$this->landuses);?>
</tbody>
</table>