<?php $this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/jquery.autocomplete.pack.js',$type='text/javascript'); ?>
<?php $this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/autocompleteinitPeople.js',$type='text/javascript'); ?>
<?php $this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/ui.datepicker.js',$type='text/javascript'); ?>
<?php $this->headLink()->appendStylesheet($this->baseUrl().'/css/autocomplete.css')
->appendStylesheet($this->baseUrl().'/css/ui.datepicker.css');?>

<?php $this->jQuery()->javascriptCaptureStart() ?>
$(document).ready(function() {
$("#datefound1").datepicker({ maxDate: '+1y'});
$("#datefound2").datepicker({ maxDate: '+1y' });
	
});

<?php $this->jQuery()->javascriptCaptureEnd() ?>
<h2>Add a new object</h2>
<p>You can copy your <a href="<?php echo $this->url(array('module' => 'database','controller' => 'artefacts','action' => 'add','copy' => 'last'),null,true);?>" 
title="Autofill form fields from last record you created" id="populate" accesskey="c">last record</a></p>
<?php
echo $this->form;
?>
