<?php
$("#rallyID").css("display","none");
$("#findofnotereason").css("display","none");
$("#hID").css("display","none");
$("#treasureID").css("display","none");
$(".hideme").css("display","none");
$(".hiderally").css("display","none");
$(".hidehoard").css("display","none");
$(".hidenote").css("display","none");
$("#reason").css("display","none");
$("#findofnote").click(function(){
if ($("#findofnote").is(":checked"))
        {
       $("#findofnotereason").show("fast");
       $(".hidenote").show("fast");
        }
        else
        {     
            $("#findofnotereason").hide("fast");
          $(".hidenote").hide("fast");

        }
      });
$("#rally").click(function(){
if ($("#rally").is(":checked"))
        {
       $("#rallyID").show("fast").css("display","inline");
	   $(".hiderally").show("fast");
        }
        else
        {     
        $("#rallyID").hide("fast");
		$(".hiderally").hide("fast");
        }
      });
$("#treasure").click(function(){
if ($("#treasure").is(":checked"))
        {
       $("#treasureID").show("fast");
       $(".hideme").show("fast");

        }
        else
        {     
            $("#treasureID").hide("fast");
            $(".hideme").hide("fast");


        }
      });
$("#hoard").click(function(){
if ($("#hoard").is(":checked"))
        {
       $("#hID").show("fast");
            $(".hidehoard").show("fast");
        }
        else
        {     
            $("#hID").hide("fast");
            $(".hidehoard").hide("fast");

        }
      });