<rdf:RDF 
xmlns:batlas="http://atlantides.org/batlas/" 
xmlns:cc="http://creativecommons.org/ns#" 
xmlns:dc="http://purl.org/dc/elements/1.1/" 
xmlns:foaf="http://xmlns.com/foaf/0.1/"
xmlns:gml="http://www.opengis.net/gml/" 
xmlns:nm="http://nomisma.org/id/" 
xmlns:ov="http://open.vocab.org/terms/" 
xmlns:owl="http://www.w3.org/2002/07/owl#" 
xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" 
xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#" 
xmlns:skos="http://www.w3.org/2008/05/skos#" 
xmlns:xhv="http://www.w3.org/1999/xhtml/vocab#" 
xmlns:xml="http://www.w3.org/XML/1998/namespace"
xmlns:pas="http://www.finds.org.uk">
xml:lang="en"
>
<pas:record rdf:about="http://nomisma.org/id/igch1546">
<pas:collection rdf:resource="http://www.finds.org.uk/database/artefacts/"/>
<pas:mint>
<rdf:Description rdf:about="http://nomisma.org/id/side">
<pas:item rdf:resource="http://numismatics.org/collection/1944.100.50910"/>
</rdf:Description>
</pas:mint>

<pas:findspot >
</pas:findspot>


</pas:record>
<rdf:Description rdf:about="http://www.finds.org.uk/database/artefacts/">
<cc:attributionURL rdf:resource="http://www.finds.org.uk"/>
<cc:attributionName>
http://nomisma.org
</cc:attributionName>
<dc:title >
finds.org.uk</dc:title>
<xhv:license rdf:resource="http://creativecommons.org/licenses/by-nc/3.0/"/>
</rdf:Description>
</rdf:RDF>