<?php
/** Controller for displaying information about tags used and generated by opencalais
* 
* @category   Pas
* @package    Pas_Controller
* @subpackage ActionAdmin
* @copyright  Copyright (c) 2011 DEJ Pett dpett @ britishmuseum . org
* @license    GNU General Public License
*/
class Database_TagsController extends Pas_Controller_ActionAdmin {
	
	protected $_opencalais;
	/** Setup the contexts by action and the ACL.
	*/	
	public function init() {
	$this->_helper->_acl->allow(null);
	$this->_flashMessenger = $this->_helper->getHelper('FlashMessenger');
	$this->_opencalais = new OpenCalaisModel();
	}
	/** Display index page
	*/	
	public function indexAction() {
	$this->view->tags = $this->_opencalais->getTagsCloud();
	$this->view->geotags = $this->_opencalais->getGeoTagCloud();
	}
	/** Tags created by opencalais
	*/	
	public function opencalaisAction() {
	if($this->_getParam('tag',false)) {
	$this->view->headTitle('All records tagged by opencalais with: ' . $this->_getParam('tag'));
	$this->view->tags = $this->_opencalais->getRecordsByTag($this->_getAllParams());
	} else {
		throw new Pas_ParamException($this->_missingParameter);
	}
	}
	/** Tags created by yahoo
	*/	
	public function geotagAction() {
	if($this->_getParam('tag',false)) {
	$this->view->headTitle('All records tagged by Yahoo! Geo Placemaker with: '.$this->_getParam('tag'));
	$this->view->tags = $this->_opencalais->getRecordsByGeoTag($this->_getAllParams());
	} else {
		throw new Pas_ParamException($this->_missingParameter);
	}
	}
}