<?php $this->jQuery()->javascriptCaptureStart() ?>
jQuery(document).ready(function($) {

 $('a[rel*=lightbox]').lightBox() 
    })
<?php $this->jQuery()->javascriptCaptureEnd() ?>
<?php 
$this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/jquery.lightbox.js',$type='text/javascript'); 

?>
<?php echo $this->partialLoop('partials/content/article.phtml',$this->contents);?>
<?php if(count($this->documents)) { ?>
<h3>Scheme publications in google doc format</h3>
<ul>
<?php foreach($this->documents as $d) {
$types = explode('/',$d['type']);
echo '<li><a href="'.$d['altlink'].'" title="View this document">'.$d['title'];
echo '</a> - <span class="pdf">'.strtoupper($types['1']).'</span></li>';}
?>
</ul>
<?php } ?>