<?php 
$this->headTitle('Full details for reverse type: ','PREPEND');
$this->headMeta('This page provides details for the fourth century reverse type known as ' .  $this->reverses['0']['type'],'dc.description')
->headMeta($this->curUrl(),'dc.identifier')
->headMeta('Daniel Pett','dc.creator')
->headMeta('The Portable Antiquities Scheme','dc.publisher')
->headMeta('CC NC-BY-SA','dc.rights');
if(count($this->reverses > 0)) {
echo $this->partialLoop('partials/numismatics/revtypedetail.phtml',$this->reverses);
}
?>
<?php if(count($this->emps)):?>
<h3>Issuers</h3>
<ul id="related">
<?php echo $this->partialLoop('partials/numismatics/revtypeemp.phtml',$this->emps);?>
</ul>
<?php endif;?>

<?php if(count($this->mints)):?>
<h3>Issuing mints</h3>
<ul id="related">
<?php echo $this->partialLoop('partials/numismatics/mints.phtml',$this->mints);?>
</ul>
<?php endif;?>

<?php if($this->images):?>
<h3>Latest examples recorded</h3>
<div id="latest">
<?php echo $this->partialLoop('partials/database/imagesPaged.phtml',$this->images);?>
</div>
<?php endif;?>