<?php 
$this->headTitle('Full details for reverse type: ','PREPEND');
$this->headMeta('This page provides details for the fourth century reverse type known as ' 
        .  $this->reverses['0']['type'],'description')
->headMeta($this->curUrl(),'dc.identifier')
->headMeta('Daniel Pett','dc.creator')
->headMeta('The Portable Antiquities Scheme','dc.publisher')
->headMeta('CC NC-BY-SA','dc.rights');
if(count($this->reverses > 0)) {
echo $this->partialLoop('partials/numismatics/revtypedetail.phtml',$this->reverses);
}
?>
<?php if(count($this->emps)):?>
<h3>Issuers</h3>
<ul >
<?php echo $this->partialLoop('partials/numismatics/revtypeemp.phtml',$this->emps);?>
</ul>
<?php endif;?>

<?php if($this->mints):?>
<h3>Issuing mints</h3>
<ul >
<?php echo $this->partialLoop('partials/numismatics/mints.phtml',$this->mints);?>
</ul>
<?php endif;?>

<?php echo $this->latestRecords('reverse:' . Zend_Controller_Front::getInstance()->getRequest()->getParam('id')); ?>
<?php 
$this->jQuery()->addJavascriptFile($this->baseUrl() . '/js/JQuery/jquery.lightbox.js',
        $type='text/javascript'); 
$this->jQuery()->javascriptCaptureStart(); ?>
jQuery(document).ready(function($) {
$('a[rel*=lightbox]').lightBox() 
});
<?php $this->jQuery()->javascriptCaptureEnd(); 
?>