<?php 
$this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/jquery.lightbox.js',$type='text/javascript');
?>
<?php $this->jQuery()->javascriptCaptureStart(); ?>
jQuery(document).ready(function($) {
 $('a[rel*=lightbox]').lightBox() 
    }
);

<?php $this->jQuery()->javascriptCaptureEnd(); ?>
<?php 

echo $this->partialLoop('partials/admin/account.phtml',$this->users);
?>
<?php if($this->images):?>
<h3 style="clear:left;">Latest examples recorded</h3>
<div id="latest">
<?php echo $this->partialLoop('partials/database/imagesPaged.phtml',$this->images);?>
</div>
<?php endif;?>