<?php $this->headMeta('A list of all people requesting an upgrade on their account status for research purpose','dc.description');
$this->headTitle('Account upgrades');
?>
<h2>Account upgrade requests</h2>
<?php if(count($this->users)):?>
<table class="stripeMe" summary="A list of people requesting upgrades">
<thead>
<tr>
<th>Username</th>
<th>Fullname</th>
<th>Role</th>
<th>Research plan</th>
<th>Actions</th>
</tr>
</thead>
<tbody>
<?php echo $this->partialLoop('partials/users/upgrades.phtml',$this->users);?>
</tbody>
</table>
<?= $this->paginationControl($this->users, 'Elastic', 'structure/pagination.phtml'); ?>
<?php else:?>
<p>It is your lucky day Odysseus, Nemo has come knocking for account upgrades! Go wrestle a lion!</p>
<?php endif;?>