<?php echo $this->partialLoop('partials/numismatics/mintDetail.phtml',$this->rommints);?>
<h3>Issuers</h3>
<p>This mint was active under the following issuers and we have recorded <?php echo $this->partialLoop('partials/countObjects.phtml',$this->counts);?>.</p>
<ul id="related">
<?php echo $this->partialLoop('partials/numismatics/issuersRomanMints.phtml',$this->actives);?>
</ul>

<?php echo $this->latestRecords('mint:'. Zend_Controller_Front::getInstance()->getRequest()->getParam('id')); ?>

<?php 
$this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/jquery.lightbox.js',$type='text/javascript'); 
$this->jQuery()->javascriptCaptureStart(); ?>
jQuery(document).ready(function($) {
$('a[rel*=lightbox]').lightBox() 
});
<?php $this->jQuery()->javascriptCaptureEnd(); ?>