<?php echo $this->partialLoop('partials/numismatics/mintDetail.phtml',$this->rommints);?>
<h3>Issuers</h3>
<p>This mint was active under the following issuers and we have recorded <?php echo $this->partialLoop('partials/countObjects.phtml',$this->counts);?>.</p>
<ul id="related">
<?php echo $this->partialLoop('partials/numismatics/issuersRomanMints.phtml',$this->actives);?>
</ul>
<?php echo $this->partialLoop('partials/numismatics/mintMap.phtml',$this->rommints);?>

<?php if($this->images):?>
<h3>Latest examples recorded</h3>
<div id="latest">
<?php echo $this->partialLoop('partials/database/imagesPaged.phtml',$this->images);?>
</div>
<?php endif;?>
