<?php 
$this->headTitle('Administer content');
if (count($this->contents)): ?>
<h2>Administer site content</h2>
<p><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'content','action' => 'add'),null,true);?>" title="">Add new content</a></p>
<table class="stripeMe" summary="All content entered on the system">
<caption>All content entered</caption>
<thead>
<tr>
<th>Title</th>
<th>Section</th>
<th>Created</th>
<th>Created by</th>
<th>Updated</th>
<th>Updated by</th>
<th>Status</th>
<th>Actions</th>
</tr>
</thead>
<tbody>
<?php echo $this->partialLoop('partials/admin/contentTable.phtml',$this->contents);?>
</tbody>
<tfoot>
<tr>
<th>Title</th>
<th>Section</th>
<th>Created</th>
<th>Created by</th>
<th>Updated</th>
<th>Updated by</th>
<th>Status</th>
<th>Actions</th>
</tr>
</tfoot>
</table>
<?php endif;?>
<?echo $this->paginationControl($this->contents, 'Sliding', 'structure/pagination.phtml'); ?>
